// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: message/outbox/v1/find-hobom-message-outbox.proto

package hobommessagepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FindHoBomMessageOutboxController_FindOutboxByEventTypeAndStatusUseCase_FullMethodName = "/outbox.message.FindHoBomMessageOutboxController/FindOutboxByEventTypeAndStatusUseCase"
)

// FindHoBomMessageOutboxControllerClient is the client API for FindHoBomMessageOutboxController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FindHoBomMessageOutboxControllerClient interface {
	FindOutboxByEventTypeAndStatusUseCase(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type findHoBomMessageOutboxControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewFindHoBomMessageOutboxControllerClient(cc grpc.ClientConnInterface) FindHoBomMessageOutboxControllerClient {
	return &findHoBomMessageOutboxControllerClient{cc}
}

func (c *findHoBomMessageOutboxControllerClient) FindOutboxByEventTypeAndStatusUseCase(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, FindHoBomMessageOutboxController_FindOutboxByEventTypeAndStatusUseCase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FindHoBomMessageOutboxControllerServer is the server API for FindHoBomMessageOutboxController service.
// All implementations must embed UnimplementedFindHoBomMessageOutboxControllerServer
// for forward compatibility.
type FindHoBomMessageOutboxControllerServer interface {
	FindOutboxByEventTypeAndStatusUseCase(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedFindHoBomMessageOutboxControllerServer()
}

// UnimplementedFindHoBomMessageOutboxControllerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFindHoBomMessageOutboxControllerServer struct{}

func (UnimplementedFindHoBomMessageOutboxControllerServer) FindOutboxByEventTypeAndStatusUseCase(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindOutboxByEventTypeAndStatusUseCase not implemented")
}
func (UnimplementedFindHoBomMessageOutboxControllerServer) mustEmbedUnimplementedFindHoBomMessageOutboxControllerServer() {
}
func (UnimplementedFindHoBomMessageOutboxControllerServer) testEmbeddedByValue() {}

// UnsafeFindHoBomMessageOutboxControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FindHoBomMessageOutboxControllerServer will
// result in compilation errors.
type UnsafeFindHoBomMessageOutboxControllerServer interface {
	mustEmbedUnimplementedFindHoBomMessageOutboxControllerServer()
}

func RegisterFindHoBomMessageOutboxControllerServer(s grpc.ServiceRegistrar, srv FindHoBomMessageOutboxControllerServer) {
	// If the following call pancis, it indicates UnimplementedFindHoBomMessageOutboxControllerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FindHoBomMessageOutboxController_ServiceDesc, srv)
}

func _FindHoBomMessageOutboxController_FindOutboxByEventTypeAndStatusUseCase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FindHoBomMessageOutboxControllerServer).FindOutboxByEventTypeAndStatusUseCase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FindHoBomMessageOutboxController_FindOutboxByEventTypeAndStatusUseCase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FindHoBomMessageOutboxControllerServer).FindOutboxByEventTypeAndStatusUseCase(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// FindHoBomMessageOutboxController_ServiceDesc is the grpc.ServiceDesc for FindHoBomMessageOutboxController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FindHoBomMessageOutboxController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "outbox.message.FindHoBomMessageOutboxController",
	HandlerType: (*FindHoBomMessageOutboxControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindOutboxByEventTypeAndStatusUseCase",
			Handler:    _FindHoBomMessageOutboxController_FindOutboxByEventTypeAndStatusUseCase_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message/outbox/v1/find-hobom-message-outbox.proto",
}
