// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: message/outbox/v1/patch-hobom-message-outbox.proto

package hobommessagepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MarkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=eventId,proto3" json:"eventId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkRequest) Reset() {
	*x = MarkRequest{}
	mi := &file_message_outbox_v1_patch_hobom_message_outbox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkRequest) ProtoMessage() {}

func (x *MarkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_outbox_v1_patch_hobom_message_outbox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkRequest.ProtoReflect.Descriptor instead.
func (*MarkRequest) Descriptor() ([]byte, []int) {
	return file_message_outbox_v1_patch_hobom_message_outbox_proto_rawDescGZIP(), []int{0}
}

func (x *MarkRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type MarkFailedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=eventId,proto3" json:"eventId,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkFailedRequest) Reset() {
	*x = MarkFailedRequest{}
	mi := &file_message_outbox_v1_patch_hobom_message_outbox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkFailedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkFailedRequest) ProtoMessage() {}

func (x *MarkFailedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_outbox_v1_patch_hobom_message_outbox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkFailedRequest.ProtoReflect.Descriptor instead.
func (*MarkFailedRequest) Descriptor() ([]byte, []int) {
	return file_message_outbox_v1_patch_hobom_message_outbox_proto_rawDescGZIP(), []int{1}
}

func (x *MarkFailedRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *MarkFailedRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_message_outbox_v1_patch_hobom_message_outbox_proto protoreflect.FileDescriptor

const file_message_outbox_v1_patch_hobom_message_outbox_proto_rawDesc = "" +
	"\n" +
	"2message/outbox/v1/patch-hobom-message-outbox.proto\x12\x0eoutbox.message\x1a\x1bgoogle/protobuf/empty.proto\"'\n" +
	"\vMarkRequest\x12\x18\n" +
	"\aeventId\x18\x01 \x01(\tR\aeventId\"Q\n" +
	"\x11MarkFailedRequest\x12\x18\n" +
	"\aeventId\x18\x01 \x01(\tR\aeventId\x12\"\n" +
	"\ferrorMessage\x18\x02 \x01(\tR\ferrorMessage2\xc9\x01\n" +
	"\x15PatchOutboxController\x12S\n" +
	"\x1cPatchOutboxMarkAsSentUseCase\x12\x1b.outbox.message.MarkRequest\x1a\x16.google.protobuf.Empty\x12[\n" +
	"\x1ePatchOutboxMarkAsFailedUseCase\x12!.outbox.message.MarkFailedRequest\x1a\x16.google.protobuf.EmptyB\\ZZgithub.com/HoBom-s/hobom-event-processor/infra/grpc/v1/hobom-message-outbox;hobommessagepbb\x06proto3"

var (
	file_message_outbox_v1_patch_hobom_message_outbox_proto_rawDescOnce sync.Once
	file_message_outbox_v1_patch_hobom_message_outbox_proto_rawDescData []byte
)

func file_message_outbox_v1_patch_hobom_message_outbox_proto_rawDescGZIP() []byte {
	file_message_outbox_v1_patch_hobom_message_outbox_proto_rawDescOnce.Do(func() {
		file_message_outbox_v1_patch_hobom_message_outbox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_outbox_v1_patch_hobom_message_outbox_proto_rawDesc), len(file_message_outbox_v1_patch_hobom_message_outbox_proto_rawDesc)))
	})
	return file_message_outbox_v1_patch_hobom_message_outbox_proto_rawDescData
}

var file_message_outbox_v1_patch_hobom_message_outbox_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_message_outbox_v1_patch_hobom_message_outbox_proto_goTypes = []any{
	(*MarkRequest)(nil),       // 0: outbox.message.MarkRequest
	(*MarkFailedRequest)(nil), // 1: outbox.message.MarkFailedRequest
	(*emptypb.Empty)(nil),     // 2: google.protobuf.Empty
}
var file_message_outbox_v1_patch_hobom_message_outbox_proto_depIdxs = []int32{
	0, // 0: outbox.message.PatchOutboxController.PatchOutboxMarkAsSentUseCase:input_type -> outbox.message.MarkRequest
	1, // 1: outbox.message.PatchOutboxController.PatchOutboxMarkAsFailedUseCase:input_type -> outbox.message.MarkFailedRequest
	2, // 2: outbox.message.PatchOutboxController.PatchOutboxMarkAsSentUseCase:output_type -> google.protobuf.Empty
	2, // 3: outbox.message.PatchOutboxController.PatchOutboxMarkAsFailedUseCase:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_message_outbox_v1_patch_hobom_message_outbox_proto_init() }
func file_message_outbox_v1_patch_hobom_message_outbox_proto_init() {
	if File_message_outbox_v1_patch_hobom_message_outbox_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_outbox_v1_patch_hobom_message_outbox_proto_rawDesc), len(file_message_outbox_v1_patch_hobom_message_outbox_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_message_outbox_v1_patch_hobom_message_outbox_proto_goTypes,
		DependencyIndexes: file_message_outbox_v1_patch_hobom_message_outbox_proto_depIdxs,
		MessageInfos:      file_message_outbox_v1_patch_hobom_message_outbox_proto_msgTypes,
	}.Build()
	File_message_outbox_v1_patch_hobom_message_outbox_proto = out.File
	file_message_outbox_v1_patch_hobom_message_outbox_proto_goTypes = nil
	file_message_outbox_v1_patch_hobom_message_outbox_proto_depIdxs = nil
}
