// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: llm/v1/ask-question.proto

package llmpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LawContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleNo     string                 `protobuf:"bytes,1,opt,name=articleNo,proto3" json:"articleNo,omitempty"`
	ArticleTitle  string                 `protobuf:"bytes,2,opt,name=articleTitle,proto3" json:"articleTitle,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LawContext) Reset() {
	*x = LawContext{}
	mi := &file_llm_v1_ask_question_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LawContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LawContext) ProtoMessage() {}

func (x *LawContext) ProtoReflect() protoreflect.Message {
	mi := &file_llm_v1_ask_question_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LawContext.ProtoReflect.Descriptor instead.
func (*LawContext) Descriptor() ([]byte, []int) {
	return file_llm_v1_ask_question_proto_rawDescGZIP(), []int{0}
}

func (x *LawContext) GetArticleNo() string {
	if x != nil {
		return x.ArticleNo
	}
	return ""
}

func (x *LawContext) GetArticleTitle() string {
	if x != nil {
		return x.ArticleTitle
	}
	return ""
}

func (x *LawContext) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type AskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      string                 `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	Articles      []*LawContext          `protobuf:"bytes,2,rep,name=articles,proto3" json:"articles,omitempty"`
	RecentChanges []*ArticleChange       `protobuf:"bytes,3,rep,name=recentChanges,proto3" json:"recentChanges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AskRequest) Reset() {
	*x = AskRequest{}
	mi := &file_llm_v1_ask_question_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskRequest) ProtoMessage() {}

func (x *AskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llm_v1_ask_question_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskRequest.ProtoReflect.Descriptor instead.
func (*AskRequest) Descriptor() ([]byte, []int) {
	return file_llm_v1_ask_question_proto_rawDescGZIP(), []int{1}
}

func (x *AskRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *AskRequest) GetArticles() []*LawContext {
	if x != nil {
		return x.Articles
	}
	return nil
}

func (x *AskRequest) GetRecentChanges() []*ArticleChange {
	if x != nil {
		return x.RecentChanges
	}
	return nil
}

type AskResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Answer             string                 `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	ReferencedArticles []string               `protobuf:"bytes,2,rep,name=referencedArticles,proto3" json:"referencedArticles,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AskResponse) Reset() {
	*x = AskResponse{}
	mi := &file_llm_v1_ask_question_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskResponse) ProtoMessage() {}

func (x *AskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llm_v1_ask_question_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskResponse.ProtoReflect.Descriptor instead.
func (*AskResponse) Descriptor() ([]byte, []int) {
	return file_llm_v1_ask_question_proto_rawDescGZIP(), []int{2}
}

func (x *AskResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *AskResponse) GetReferencedArticles() []string {
	if x != nil {
		return x.ReferencedArticles
	}
	return nil
}

var File_llm_v1_ask_question_proto protoreflect.FileDescriptor

const file_llm_v1_ask_question_proto_rawDesc = "" +
	"\n" +
	"\x19llm/v1/ask-question.proto\x12\x03llm\x1a$llm/v1/generate-study-material.proto\"h\n" +
	"\n" +
	"LawContext\x12\x1c\n" +
	"\tarticleNo\x18\x01 \x01(\tR\tarticleNo\x12\"\n" +
	"\farticleTitle\x18\x02 \x01(\tR\farticleTitle\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"\x8f\x01\n" +
	"\n" +
	"AskRequest\x12\x1a\n" +
	"\bquestion\x18\x01 \x01(\tR\bquestion\x12+\n" +
	"\barticles\x18\x02 \x03(\v2\x0f.llm.LawContextR\barticles\x128\n" +
	"\rrecentChanges\x18\x03 \x03(\v2\x12.llm.ArticleChangeR\rrecentChanges\"U\n" +
	"\vAskResponse\x12\x16\n" +
	"\x06answer\x18\x01 \x01(\tR\x06answer\x12.\n" +
	"\x12referencedArticles\x18\x02 \x03(\tR\x12referencedArticles2>\n" +
	"\x12AskQuestionService\x12(\n" +
	"\x03Ask\x12\x0f.llm.AskRequest\x1a\x10.llm.AskResponseBFZDgithub.com/HoBom-s/hobom-llm-service-backend/infra/grpc/v1/llm;llmpbb\x06proto3"

var (
	file_llm_v1_ask_question_proto_rawDescOnce sync.Once
	file_llm_v1_ask_question_proto_rawDescData []byte
)

func file_llm_v1_ask_question_proto_rawDescGZIP() []byte {
	file_llm_v1_ask_question_proto_rawDescOnce.Do(func() {
		file_llm_v1_ask_question_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_llm_v1_ask_question_proto_rawDesc), len(file_llm_v1_ask_question_proto_rawDesc)))
	})
	return file_llm_v1_ask_question_proto_rawDescData
}

var file_llm_v1_ask_question_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_llm_v1_ask_question_proto_goTypes = []any{
	(*LawContext)(nil),    // 0: llm.LawContext
	(*AskRequest)(nil),    // 1: llm.AskRequest
	(*AskResponse)(nil),   // 2: llm.AskResponse
	(*ArticleChange)(nil), // 3: llm.ArticleChange
}
var file_llm_v1_ask_question_proto_depIdxs = []int32{
	0, // 0: llm.AskRequest.articles:type_name -> llm.LawContext
	3, // 1: llm.AskRequest.recentChanges:type_name -> llm.ArticleChange
	1, // 2: llm.AskQuestionService.Ask:input_type -> llm.AskRequest
	2, // 3: llm.AskQuestionService.Ask:output_type -> llm.AskResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_llm_v1_ask_question_proto_init() }
func file_llm_v1_ask_question_proto_init() {
	if File_llm_v1_ask_question_proto != nil {
		return
	}
	file_llm_v1_generate_study_material_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_llm_v1_ask_question_proto_rawDesc), len(file_llm_v1_ask_question_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_llm_v1_ask_question_proto_goTypes,
		DependencyIndexes: file_llm_v1_ask_question_proto_depIdxs,
		MessageInfos:      file_llm_v1_ask_question_proto_msgTypes,
	}.Build()
	File_llm_v1_ask_question_proto = out.File
	file_llm_v1_ask_question_proto_goTypes = nil
	file_llm_v1_ask_question_proto_depIdxs = nil
}
