// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        (unknown)
// source: llm/v1/ask-question.proto

package llmpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LawContext struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ArticleNo    string `protobuf:"bytes,1,opt,name=articleNo,proto3" json:"articleNo,omitempty"`
	ArticleTitle string `protobuf:"bytes,2,opt,name=articleTitle,proto3" json:"articleTitle,omitempty"`
	Content      string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *LawContext) Reset() {
	*x = LawContext{}
	if protoimpl.UnsafeEnabled {
		mi := &file_llm_v1_ask_question_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LawContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LawContext) ProtoMessage() {}

func (x *LawContext) ProtoReflect() protoreflect.Message {
	mi := &file_llm_v1_ask_question_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LawContext.ProtoReflect.Descriptor instead.
func (*LawContext) Descriptor() ([]byte, []int) {
	return file_llm_v1_ask_question_proto_rawDescGZIP(), []int{0}
}

func (x *LawContext) GetArticleNo() string {
	if x != nil {
		return x.ArticleNo
	}
	return ""
}

func (x *LawContext) GetArticleTitle() string {
	if x != nil {
		return x.ArticleTitle
	}
	return ""
}

func (x *LawContext) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type AskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Question      string           `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	Articles      []*LawContext    `protobuf:"bytes,2,rep,name=articles,proto3" json:"articles,omitempty"`
	RecentChanges []*ArticleChange `protobuf:"bytes,3,rep,name=recentChanges,proto3" json:"recentChanges,omitempty"`
}

func (x *AskRequest) Reset() {
	*x = AskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_llm_v1_ask_question_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskRequest) ProtoMessage() {}

func (x *AskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llm_v1_ask_question_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskRequest.ProtoReflect.Descriptor instead.
func (*AskRequest) Descriptor() ([]byte, []int) {
	return file_llm_v1_ask_question_proto_rawDescGZIP(), []int{1}
}

func (x *AskRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *AskRequest) GetArticles() []*LawContext {
	if x != nil {
		return x.Articles
	}
	return nil
}

func (x *AskRequest) GetRecentChanges() []*ArticleChange {
	if x != nil {
		return x.RecentChanges
	}
	return nil
}

type AskResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Answer             string   `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	ReferencedArticles []string `protobuf:"bytes,2,rep,name=referencedArticles,proto3" json:"referencedArticles,omitempty"`
}

func (x *AskResponse) Reset() {
	*x = AskResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_llm_v1_ask_question_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskResponse) ProtoMessage() {}

func (x *AskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llm_v1_ask_question_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskResponse.ProtoReflect.Descriptor instead.
func (*AskResponse) Descriptor() ([]byte, []int) {
	return file_llm_v1_ask_question_proto_rawDescGZIP(), []int{2}
}

func (x *AskResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *AskResponse) GetReferencedArticles() []string {
	if x != nil {
		return x.ReferencedArticles
	}
	return nil
}

var File_llm_v1_ask_question_proto protoreflect.FileDescriptor

var file_llm_v1_ask_question_proto_rawDesc = []byte{
	0x0a, 0x19, 0x6c, 0x6c, 0x6d, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x73, 0x6b, 0x2d, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6c, 0x6c, 0x6d,
	0x1a, 0x24, 0x6c, 0x6c, 0x6d, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74,
	0x65, 0x2d, 0x73, 0x74, 0x75, 0x64, 0x79, 0x2d, 0x6d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x68, 0x0a, 0x0a, 0x4c, 0x61, 0x77, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x78, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x4e,
	0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65,
	0x4e, 0x6f, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x54, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c,
	0x65, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x22, 0x8f, 0x01, 0x0a, 0x0a, 0x41, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2b, 0x0a, 0x08, 0x61,
	0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x6c, 0x6c, 0x6d, 0x2e, 0x4c, 0x61, 0x77, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x52, 0x08,
	0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x73, 0x12, 0x38, 0x0a, 0x0d, 0x72, 0x65, 0x63, 0x65,
	0x6e, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x6c, 0x6c, 0x6d, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x52, 0x0d, 0x72, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x73, 0x22, 0x55, 0x0a, 0x0b, 0x41, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x2e, 0x0a, 0x12, 0x72, 0x65, 0x66,
	0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x64, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x12, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65,
	0x64, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x73, 0x32, 0x3e, 0x0a, 0x12, 0x41, 0x73, 0x6b,
	0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x28, 0x0a, 0x03, 0x41, 0x73, 0x6b, 0x12, 0x0f, 0x2e, 0x6c, 0x6c, 0x6d, 0x2e, 0x41, 0x73, 0x6b,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x6c, 0x6c, 0x6d, 0x2e, 0x41, 0x73,
	0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x46, 0x5a, 0x44, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x48, 0x6f, 0x42, 0x6f, 0x6d, 0x2d, 0x73, 0x2f,
	0x68, 0x6f, 0x62, 0x6f, 0x6d, 0x2d, 0x6c, 0x6c, 0x6d, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2d, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x2f,
	0x67, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x31, 0x2f, 0x6c, 0x6c, 0x6d, 0x3b, 0x6c, 0x6c, 0x6d, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_llm_v1_ask_question_proto_rawDescOnce sync.Once
	file_llm_v1_ask_question_proto_rawDescData = file_llm_v1_ask_question_proto_rawDesc
)

func file_llm_v1_ask_question_proto_rawDescGZIP() []byte {
	file_llm_v1_ask_question_proto_rawDescOnce.Do(func() {
		file_llm_v1_ask_question_proto_rawDescData = protoimpl.X.CompressGZIP(file_llm_v1_ask_question_proto_rawDescData)
	})
	return file_llm_v1_ask_question_proto_rawDescData
}

var file_llm_v1_ask_question_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_llm_v1_ask_question_proto_goTypes = []interface{}{
	(*LawContext)(nil),    // 0: llm.LawContext
	(*AskRequest)(nil),    // 1: llm.AskRequest
	(*AskResponse)(nil),   // 2: llm.AskResponse
	(*ArticleChange)(nil), // 3: llm.ArticleChange
}
var file_llm_v1_ask_question_proto_depIdxs = []int32{
	0, // 0: llm.AskRequest.articles:type_name -> llm.LawContext
	3, // 1: llm.AskRequest.recentChanges:type_name -> llm.ArticleChange
	1, // 2: llm.AskQuestionService.Ask:input_type -> llm.AskRequest
	2, // 3: llm.AskQuestionService.Ask:output_type -> llm.AskResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_llm_v1_ask_question_proto_init() }
func file_llm_v1_ask_question_proto_init() {
	if File_llm_v1_ask_question_proto != nil {
		return
	}
	file_llm_v1_generate_study_material_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_llm_v1_ask_question_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LawContext); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_llm_v1_ask_question_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_llm_v1_ask_question_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AskResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_llm_v1_ask_question_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_llm_v1_ask_question_proto_goTypes,
		DependencyIndexes: file_llm_v1_ask_question_proto_depIdxs,
		MessageInfos:      file_llm_v1_ask_question_proto_msgTypes,
	}.Build()
	File_llm_v1_ask_question_proto = out.File
	file_llm_v1_ask_question_proto_rawDesc = nil
	file_llm_v1_ask_question_proto_goTypes = nil
	file_llm_v1_ask_question_proto_depIdxs = nil
}
