// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: llm/v1/ask-question.proto

package llmpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AskQuestionService_Ask_FullMethodName = "/llm.AskQuestionService/Ask"
)

// AskQuestionServiceClient is the client API for AskQuestionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AskQuestionServiceClient interface {
	Ask(ctx context.Context, in *AskRequest, opts ...grpc.CallOption) (*AskResponse, error)
}

type askQuestionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAskQuestionServiceClient(cc grpc.ClientConnInterface) AskQuestionServiceClient {
	return &askQuestionServiceClient{cc}
}

func (c *askQuestionServiceClient) Ask(ctx context.Context, in *AskRequest, opts ...grpc.CallOption) (*AskResponse, error) {
	out := new(AskResponse)
	err := c.cc.Invoke(ctx, AskQuestionService_Ask_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AskQuestionServiceServer is the server API for AskQuestionService service.
// All implementations must embed UnimplementedAskQuestionServiceServer
// for forward compatibility
type AskQuestionServiceServer interface {
	Ask(context.Context, *AskRequest) (*AskResponse, error)
	mustEmbedUnimplementedAskQuestionServiceServer()
}

// UnimplementedAskQuestionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAskQuestionServiceServer struct {
}

func (UnimplementedAskQuestionServiceServer) Ask(context.Context, *AskRequest) (*AskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ask not implemented")
}
func (UnimplementedAskQuestionServiceServer) mustEmbedUnimplementedAskQuestionServiceServer() {}

// UnsafeAskQuestionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AskQuestionServiceServer will
// result in compilation errors.
type UnsafeAskQuestionServiceServer interface {
	mustEmbedUnimplementedAskQuestionServiceServer()
}

func RegisterAskQuestionServiceServer(s grpc.ServiceRegistrar, srv AskQuestionServiceServer) {
	s.RegisterService(&AskQuestionService_ServiceDesc, srv)
}

func _AskQuestionService_Ask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AskQuestionServiceServer).Ask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AskQuestionService_Ask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AskQuestionServiceServer).Ask(ctx, req.(*AskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AskQuestionService_ServiceDesc is the grpc.ServiceDesc for AskQuestionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AskQuestionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "llm.AskQuestionService",
	HandlerType: (*AskQuestionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ask",
			Handler:    _AskQuestionService_Ask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "llm/v1/ask-question.proto",
}
