// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        (unknown)
// source: llm/v1/generate-study-material.proto

package llmpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ArticleChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ArticleNo  string `protobuf:"bytes,1,opt,name=articleNo,proto3" json:"articleNo,omitempty"`
	ChangeType string `protobuf:"bytes,2,opt,name=changeType,proto3" json:"changeType,omitempty"`
	Before     string `protobuf:"bytes,3,opt,name=before,proto3" json:"before,omitempty"`
	After      string `protobuf:"bytes,4,opt,name=after,proto3" json:"after,omitempty"`
}

func (x *ArticleChange) Reset() {
	*x = ArticleChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_llm_v1_generate_study_material_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArticleChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleChange) ProtoMessage() {}

func (x *ArticleChange) ProtoReflect() protoreflect.Message {
	mi := &file_llm_v1_generate_study_material_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleChange.ProtoReflect.Descriptor instead.
func (*ArticleChange) Descriptor() ([]byte, []int) {
	return file_llm_v1_generate_study_material_proto_rawDescGZIP(), []int{0}
}

func (x *ArticleChange) GetArticleNo() string {
	if x != nil {
		return x.ArticleNo
	}
	return ""
}

func (x *ArticleChange) GetChangeType() string {
	if x != nil {
		return x.ChangeType
	}
	return ""
}

func (x *ArticleChange) GetBefore() string {
	if x != nil {
		return x.Before
	}
	return ""
}

func (x *ArticleChange) GetAfter() string {
	if x != nil {
		return x.After
	}
	return ""
}

type StudyMaterialRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Changes []*ArticleChange `protobuf:"bytes,1,rep,name=changes,proto3" json:"changes,omitempty"`
}

func (x *StudyMaterialRequest) Reset() {
	*x = StudyMaterialRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_llm_v1_generate_study_material_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StudyMaterialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudyMaterialRequest) ProtoMessage() {}

func (x *StudyMaterialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llm_v1_generate_study_material_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudyMaterialRequest.ProtoReflect.Descriptor instead.
func (*StudyMaterialRequest) Descriptor() ([]byte, []int) {
	return file_llm_v1_generate_study_material_proto_rawDescGZIP(), []int{1}
}

func (x *StudyMaterialRequest) GetChanges() []*ArticleChange {
	if x != nil {
		return x.Changes
	}
	return nil
}

type Quiz struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type        string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Question    string   `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	Answer      string   `protobuf:"bytes,3,opt,name=answer,proto3" json:"answer,omitempty"`
	Explanation string   `protobuf:"bytes,4,opt,name=explanation,proto3" json:"explanation,omitempty"`
	Choices     []string `protobuf:"bytes,5,rep,name=choices,proto3" json:"choices,omitempty"`
}

func (x *Quiz) Reset() {
	*x = Quiz{}
	if protoimpl.UnsafeEnabled {
		mi := &file_llm_v1_generate_study_material_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Quiz) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quiz) ProtoMessage() {}

func (x *Quiz) ProtoReflect() protoreflect.Message {
	mi := &file_llm_v1_generate_study_material_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quiz.ProtoReflect.Descriptor instead.
func (*Quiz) Descriptor() ([]byte, []int) {
	return file_llm_v1_generate_study_material_proto_rawDescGZIP(), []int{2}
}

func (x *Quiz) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Quiz) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *Quiz) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *Quiz) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

func (x *Quiz) GetChoices() []string {
	if x != nil {
		return x.Choices
	}
	return nil
}

type StudyMaterialResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Summary   string   `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	KeyPoints []string `protobuf:"bytes,2,rep,name=keyPoints,proto3" json:"keyPoints,omitempty"`
	Quizzes   []*Quiz  `protobuf:"bytes,3,rep,name=quizzes,proto3" json:"quizzes,omitempty"`
}

func (x *StudyMaterialResponse) Reset() {
	*x = StudyMaterialResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_llm_v1_generate_study_material_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StudyMaterialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudyMaterialResponse) ProtoMessage() {}

func (x *StudyMaterialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llm_v1_generate_study_material_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudyMaterialResponse.ProtoReflect.Descriptor instead.
func (*StudyMaterialResponse) Descriptor() ([]byte, []int) {
	return file_llm_v1_generate_study_material_proto_rawDescGZIP(), []int{3}
}

func (x *StudyMaterialResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *StudyMaterialResponse) GetKeyPoints() []string {
	if x != nil {
		return x.KeyPoints
	}
	return nil
}

func (x *StudyMaterialResponse) GetQuizzes() []*Quiz {
	if x != nil {
		return x.Quizzes
	}
	return nil
}

var File_llm_v1_generate_study_material_proto protoreflect.FileDescriptor

var file_llm_v1_generate_study_material_proto_rawDesc = []byte{
	0x0a, 0x24, 0x6c, 0x6c, 0x6d, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74,
	0x65, 0x2d, 0x73, 0x74, 0x75, 0x64, 0x79, 0x2d, 0x6d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6c, 0x6c, 0x6d, 0x22, 0x7b, 0x0a, 0x0d, 0x41,
	0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x4e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x4e, 0x6f, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x65,
	0x66, 0x6f, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x65, 0x66, 0x6f,
	0x72, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x66, 0x74, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x61, 0x66, 0x74, 0x65, 0x72, 0x22, 0x44, 0x0a, 0x14, 0x53, 0x74, 0x75, 0x64,
	0x79, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x2c, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x6c, 0x6c, 0x6d, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x22, 0x8a,
	0x01, 0x0a, 0x04, 0x51, 0x75, 0x69, 0x7a, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12,
	0x20, 0x0a, 0x0b, 0x65, 0x78, 0x70, 0x6c, 0x61, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x65, 0x78, 0x70, 0x6c, 0x61, 0x6e, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x07, 0x63, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x73, 0x22, 0x74, 0x0a, 0x15, 0x53,
	0x74, 0x75, 0x64, 0x79, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x1c,
	0x0a, 0x09, 0x6b, 0x65, 0x79, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x09, 0x6b, 0x65, 0x79, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x23, 0x0a, 0x07,
	0x71, 0x75, 0x69, 0x7a, 0x7a, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e,
	0x6c, 0x6c, 0x6d, 0x2e, 0x51, 0x75, 0x69, 0x7a, 0x52, 0x07, 0x71, 0x75, 0x69, 0x7a, 0x7a, 0x65,
	0x73, 0x32, 0x59, 0x0a, 0x14, 0x53, 0x74, 0x75, 0x64, 0x79, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69,
	0x61, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x41, 0x0a, 0x08, 0x47, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x12, 0x19, 0x2e, 0x6c, 0x6c, 0x6d, 0x2e, 0x53, 0x74, 0x75, 0x64,
	0x79, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1a, 0x2e, 0x6c, 0x6c, 0x6d, 0x2e, 0x53, 0x74, 0x75, 0x64, 0x79, 0x4d, 0x61, 0x74, 0x65,
	0x72, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x46, 0x5a, 0x44,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x48, 0x6f, 0x42, 0x6f, 0x6d,
	0x2d, 0x73, 0x2f, 0x68, 0x6f, 0x62, 0x6f, 0x6d, 0x2d, 0x6c, 0x6c, 0x6d, 0x2d, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2d, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x69, 0x6e, 0x66,
	0x72, 0x61, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x31, 0x2f, 0x6c, 0x6c, 0x6d, 0x3b, 0x6c,
	0x6c, 0x6d, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_llm_v1_generate_study_material_proto_rawDescOnce sync.Once
	file_llm_v1_generate_study_material_proto_rawDescData = file_llm_v1_generate_study_material_proto_rawDesc
)

func file_llm_v1_generate_study_material_proto_rawDescGZIP() []byte {
	file_llm_v1_generate_study_material_proto_rawDescOnce.Do(func() {
		file_llm_v1_generate_study_material_proto_rawDescData = protoimpl.X.CompressGZIP(file_llm_v1_generate_study_material_proto_rawDescData)
	})
	return file_llm_v1_generate_study_material_proto_rawDescData
}

var file_llm_v1_generate_study_material_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_llm_v1_generate_study_material_proto_goTypes = []interface{}{
	(*ArticleChange)(nil),         // 0: llm.ArticleChange
	(*StudyMaterialRequest)(nil),  // 1: llm.StudyMaterialRequest
	(*Quiz)(nil),                  // 2: llm.Quiz
	(*StudyMaterialResponse)(nil), // 3: llm.StudyMaterialResponse
}
var file_llm_v1_generate_study_material_proto_depIdxs = []int32{
	0, // 0: llm.StudyMaterialRequest.changes:type_name -> llm.ArticleChange
	2, // 1: llm.StudyMaterialResponse.quizzes:type_name -> llm.Quiz
	1, // 2: llm.StudyMaterialService.Generate:input_type -> llm.StudyMaterialRequest
	3, // 3: llm.StudyMaterialService.Generate:output_type -> llm.StudyMaterialResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_llm_v1_generate_study_material_proto_init() }
func file_llm_v1_generate_study_material_proto_init() {
	if File_llm_v1_generate_study_material_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_llm_v1_generate_study_material_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArticleChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_llm_v1_generate_study_material_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StudyMaterialRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_llm_v1_generate_study_material_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Quiz); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_llm_v1_generate_study_material_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StudyMaterialResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_llm_v1_generate_study_material_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_llm_v1_generate_study_material_proto_goTypes,
		DependencyIndexes: file_llm_v1_generate_study_material_proto_depIdxs,
		MessageInfos:      file_llm_v1_generate_study_material_proto_msgTypes,
	}.Build()
	File_llm_v1_generate_study_material_proto = out.File
	file_llm_v1_generate_study_material_proto_rawDesc = nil
	file_llm_v1_generate_study_material_proto_goTypes = nil
	file_llm_v1_generate_study_material_proto_depIdxs = nil
}
