// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: llm/v1/generate-study-material.proto

package llmpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	StudyMaterialService_Generate_FullMethodName = "/llm.StudyMaterialService/Generate"
)

// StudyMaterialServiceClient is the client API for StudyMaterialService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StudyMaterialServiceClient interface {
	Generate(ctx context.Context, in *StudyMaterialRequest, opts ...grpc.CallOption) (*StudyMaterialResponse, error)
}

type studyMaterialServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStudyMaterialServiceClient(cc grpc.ClientConnInterface) StudyMaterialServiceClient {
	return &studyMaterialServiceClient{cc}
}

func (c *studyMaterialServiceClient) Generate(ctx context.Context, in *StudyMaterialRequest, opts ...grpc.CallOption) (*StudyMaterialResponse, error) {
	out := new(StudyMaterialResponse)
	err := c.cc.Invoke(ctx, StudyMaterialService_Generate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StudyMaterialServiceServer is the server API for StudyMaterialService service.
// All implementations must embed UnimplementedStudyMaterialServiceServer
// for forward compatibility
type StudyMaterialServiceServer interface {
	Generate(context.Context, *StudyMaterialRequest) (*StudyMaterialResponse, error)
	mustEmbedUnimplementedStudyMaterialServiceServer()
}

// UnimplementedStudyMaterialServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStudyMaterialServiceServer struct {
}

func (UnimplementedStudyMaterialServiceServer) Generate(context.Context, *StudyMaterialRequest) (*StudyMaterialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Generate not implemented")
}
func (UnimplementedStudyMaterialServiceServer) mustEmbedUnimplementedStudyMaterialServiceServer() {}

// UnsafeStudyMaterialServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StudyMaterialServiceServer will
// result in compilation errors.
type UnsafeStudyMaterialServiceServer interface {
	mustEmbedUnimplementedStudyMaterialServiceServer()
}

func RegisterStudyMaterialServiceServer(s grpc.ServiceRegistrar, srv StudyMaterialServiceServer) {
	s.RegisterService(&StudyMaterialService_ServiceDesc, srv)
}

func _StudyMaterialService_Generate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StudyMaterialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudyMaterialServiceServer).Generate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StudyMaterialService_Generate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudyMaterialServiceServer).Generate(ctx, req.(*StudyMaterialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StudyMaterialService_ServiceDesc is the grpc.ServiceDesc for StudyMaterialService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StudyMaterialService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "llm.StudyMaterialService",
	HandlerType: (*StudyMaterialServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Generate",
			Handler:    _StudyMaterialService_Generate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "llm/v1/generate-study-material.proto",
}
