// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: llm/v1/generate-study-material.proto

package llmpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ArticleChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleNo     string                 `protobuf:"bytes,1,opt,name=articleNo,proto3" json:"articleNo,omitempty"`
	ChangeType    string                 `protobuf:"bytes,2,opt,name=changeType,proto3" json:"changeType,omitempty"`
	Before        string                 `protobuf:"bytes,3,opt,name=before,proto3" json:"before,omitempty"`
	After         string                 `protobuf:"bytes,4,opt,name=after,proto3" json:"after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleChange) Reset() {
	*x = ArticleChange{}
	mi := &file_llm_v1_generate_study_material_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleChange) ProtoMessage() {}

func (x *ArticleChange) ProtoReflect() protoreflect.Message {
	mi := &file_llm_v1_generate_study_material_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleChange.ProtoReflect.Descriptor instead.
func (*ArticleChange) Descriptor() ([]byte, []int) {
	return file_llm_v1_generate_study_material_proto_rawDescGZIP(), []int{0}
}

func (x *ArticleChange) GetArticleNo() string {
	if x != nil {
		return x.ArticleNo
	}
	return ""
}

func (x *ArticleChange) GetChangeType() string {
	if x != nil {
		return x.ChangeType
	}
	return ""
}

func (x *ArticleChange) GetBefore() string {
	if x != nil {
		return x.Before
	}
	return ""
}

func (x *ArticleChange) GetAfter() string {
	if x != nil {
		return x.After
	}
	return ""
}

type StudyMaterialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Changes       []*ArticleChange       `protobuf:"bytes,1,rep,name=changes,proto3" json:"changes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudyMaterialRequest) Reset() {
	*x = StudyMaterialRequest{}
	mi := &file_llm_v1_generate_study_material_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudyMaterialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudyMaterialRequest) ProtoMessage() {}

func (x *StudyMaterialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llm_v1_generate_study_material_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudyMaterialRequest.ProtoReflect.Descriptor instead.
func (*StudyMaterialRequest) Descriptor() ([]byte, []int) {
	return file_llm_v1_generate_study_material_proto_rawDescGZIP(), []int{1}
}

func (x *StudyMaterialRequest) GetChanges() []*ArticleChange {
	if x != nil {
		return x.Changes
	}
	return nil
}

type Quiz struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Question      string                 `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	Answer        string                 `protobuf:"bytes,3,opt,name=answer,proto3" json:"answer,omitempty"`
	Explanation   string                 `protobuf:"bytes,4,opt,name=explanation,proto3" json:"explanation,omitempty"`
	Choices       []string               `protobuf:"bytes,5,rep,name=choices,proto3" json:"choices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Quiz) Reset() {
	*x = Quiz{}
	mi := &file_llm_v1_generate_study_material_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quiz) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quiz) ProtoMessage() {}

func (x *Quiz) ProtoReflect() protoreflect.Message {
	mi := &file_llm_v1_generate_study_material_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quiz.ProtoReflect.Descriptor instead.
func (*Quiz) Descriptor() ([]byte, []int) {
	return file_llm_v1_generate_study_material_proto_rawDescGZIP(), []int{2}
}

func (x *Quiz) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Quiz) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *Quiz) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *Quiz) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

func (x *Quiz) GetChoices() []string {
	if x != nil {
		return x.Choices
	}
	return nil
}

type StudyMaterialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       string                 `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	KeyPoints     []string               `protobuf:"bytes,2,rep,name=keyPoints,proto3" json:"keyPoints,omitempty"`
	Quizzes       []*Quiz                `protobuf:"bytes,3,rep,name=quizzes,proto3" json:"quizzes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudyMaterialResponse) Reset() {
	*x = StudyMaterialResponse{}
	mi := &file_llm_v1_generate_study_material_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudyMaterialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudyMaterialResponse) ProtoMessage() {}

func (x *StudyMaterialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llm_v1_generate_study_material_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudyMaterialResponse.ProtoReflect.Descriptor instead.
func (*StudyMaterialResponse) Descriptor() ([]byte, []int) {
	return file_llm_v1_generate_study_material_proto_rawDescGZIP(), []int{3}
}

func (x *StudyMaterialResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *StudyMaterialResponse) GetKeyPoints() []string {
	if x != nil {
		return x.KeyPoints
	}
	return nil
}

func (x *StudyMaterialResponse) GetQuizzes() []*Quiz {
	if x != nil {
		return x.Quizzes
	}
	return nil
}

var File_llm_v1_generate_study_material_proto protoreflect.FileDescriptor

const file_llm_v1_generate_study_material_proto_rawDesc = "" +
	"\n" +
	"$llm/v1/generate-study-material.proto\x12\x03llm\"{\n" +
	"\rArticleChange\x12\x1c\n" +
	"\tarticleNo\x18\x01 \x01(\tR\tarticleNo\x12\x1e\n" +
	"\n" +
	"changeType\x18\x02 \x01(\tR\n" +
	"changeType\x12\x16\n" +
	"\x06before\x18\x03 \x01(\tR\x06before\x12\x14\n" +
	"\x05after\x18\x04 \x01(\tR\x05after\"D\n" +
	"\x14StudyMaterialRequest\x12,\n" +
	"\achanges\x18\x01 \x03(\v2\x12.llm.ArticleChangeR\achanges\"\x8a\x01\n" +
	"\x04Quiz\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1a\n" +
	"\bquestion\x18\x02 \x01(\tR\bquestion\x12\x16\n" +
	"\x06answer\x18\x03 \x01(\tR\x06answer\x12 \n" +
	"\vexplanation\x18\x04 \x01(\tR\vexplanation\x12\x18\n" +
	"\achoices\x18\x05 \x03(\tR\achoices\"t\n" +
	"\x15StudyMaterialResponse\x12\x18\n" +
	"\asummary\x18\x01 \x01(\tR\asummary\x12\x1c\n" +
	"\tkeyPoints\x18\x02 \x03(\tR\tkeyPoints\x12#\n" +
	"\aquizzes\x18\x03 \x03(\v2\t.llm.QuizR\aquizzes2Y\n" +
	"\x14StudyMaterialService\x12A\n" +
	"\bGenerate\x12\x19.llm.StudyMaterialRequest\x1a\x1a.llm.StudyMaterialResponseBFZDgithub.com/HoBom-s/hobom-llm-service-backend/infra/grpc/v1/llm;llmpbb\x06proto3"

var (
	file_llm_v1_generate_study_material_proto_rawDescOnce sync.Once
	file_llm_v1_generate_study_material_proto_rawDescData []byte
)

func file_llm_v1_generate_study_material_proto_rawDescGZIP() []byte {
	file_llm_v1_generate_study_material_proto_rawDescOnce.Do(func() {
		file_llm_v1_generate_study_material_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_llm_v1_generate_study_material_proto_rawDesc), len(file_llm_v1_generate_study_material_proto_rawDesc)))
	})
	return file_llm_v1_generate_study_material_proto_rawDescData
}

var file_llm_v1_generate_study_material_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_llm_v1_generate_study_material_proto_goTypes = []any{
	(*ArticleChange)(nil),         // 0: llm.ArticleChange
	(*StudyMaterialRequest)(nil),  // 1: llm.StudyMaterialRequest
	(*Quiz)(nil),                  // 2: llm.Quiz
	(*StudyMaterialResponse)(nil), // 3: llm.StudyMaterialResponse
}
var file_llm_v1_generate_study_material_proto_depIdxs = []int32{
	0, // 0: llm.StudyMaterialRequest.changes:type_name -> llm.ArticleChange
	2, // 1: llm.StudyMaterialResponse.quizzes:type_name -> llm.Quiz
	1, // 2: llm.StudyMaterialService.Generate:input_type -> llm.StudyMaterialRequest
	3, // 3: llm.StudyMaterialService.Generate:output_type -> llm.StudyMaterialResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_llm_v1_generate_study_material_proto_init() }
func file_llm_v1_generate_study_material_proto_init() {
	if File_llm_v1_generate_study_material_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_llm_v1_generate_study_material_proto_rawDesc), len(file_llm_v1_generate_study_material_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_llm_v1_generate_study_material_proto_goTypes,
		DependencyIndexes: file_llm_v1_generate_study_material_proto_depIdxs,
		MessageInfos:      file_llm_v1_generate_study_material_proto_msgTypes,
	}.Build()
	File_llm_v1_generate_study_material_proto = out.File
	file_llm_v1_generate_study_material_proto_goTypes = nil
	file_llm_v1_generate_study_material_proto_depIdxs = nil
}
