// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: log/outbox/v1/hobom-log-outbox.proto

package hobomlogpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=eventType,proto3" json:"eventType,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_log_outbox_v1_hobom_log_outbox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_log_outbox_v1_hobom_log_outbox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_log_outbox_v1_hobom_log_outbox_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *Request) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*QueryResult         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_log_outbox_v1_hobom_log_outbox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_log_outbox_v1_hobom_log_outbox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_log_outbox_v1_hobom_log_outbox_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetItems() []*QueryResult {
	if x != nil {
		return x.Items
	}
	return nil
}

type QueryResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=eventId,proto3" json:"eventId,omitempty"`
	EventType     string                 `protobuf:"bytes,3,opt,name=eventType,proto3" json:"eventType,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	RetryCount    int32                  `protobuf:"varint,5,opt,name=retryCount,proto3" json:"retryCount,omitempty"`
	SentAt        string                 `protobuf:"bytes,6,opt,name=sentAt,proto3" json:"sentAt,omitempty"`
	FailedAt      string                 `protobuf:"bytes,7,opt,name=failedAt,proto3" json:"failedAt,omitempty"`
	LastError     string                 `protobuf:"bytes,8,opt,name=lastError,proto3" json:"lastError,omitempty"`
	Version       int32                  `protobuf:"varint,9,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,10,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,11,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	Payload       *HoBomLogPayload       `protobuf:"bytes,12,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResult) Reset() {
	*x = QueryResult{}
	mi := &file_log_outbox_v1_hobom_log_outbox_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResult) ProtoMessage() {}

func (x *QueryResult) ProtoReflect() protoreflect.Message {
	mi := &file_log_outbox_v1_hobom_log_outbox_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResult.ProtoReflect.Descriptor instead.
func (*QueryResult) Descriptor() ([]byte, []int) {
	return file_log_outbox_v1_hobom_log_outbox_proto_rawDescGZIP(), []int{2}
}

func (x *QueryResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QueryResult) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *QueryResult) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *QueryResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *QueryResult) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *QueryResult) GetSentAt() string {
	if x != nil {
		return x.SentAt
	}
	return ""
}

func (x *QueryResult) GetFailedAt() string {
	if x != nil {
		return x.FailedAt
	}
	return ""
}

func (x *QueryResult) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *QueryResult) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *QueryResult) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *QueryResult) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *QueryResult) GetPayload() *HoBomLogPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type HoBomLogPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=traceId,proto3" json:"traceId,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	StatusCode    int32                  `protobuf:"varint,5,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Host          string                 `protobuf:"bytes,6,opt,name=host,proto3" json:"host,omitempty"`
	UserId        string                 `protobuf:"bytes,7,opt,name=userId,proto3" json:"userId,omitempty"`
	Payload       *LogPayloadDetail      `protobuf:"bytes,8,opt,name=payload,proto3" json:"payload,omitempty"`
	ServiceType   string                 `protobuf:"bytes,9,opt,name=serviceType,proto3" json:"serviceType,omitempty"`
	Message       string                 `protobuf:"bytes,10,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HoBomLogPayload) Reset() {
	*x = HoBomLogPayload{}
	mi := &file_log_outbox_v1_hobom_log_outbox_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HoBomLogPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HoBomLogPayload) ProtoMessage() {}

func (x *HoBomLogPayload) ProtoReflect() protoreflect.Message {
	mi := &file_log_outbox_v1_hobom_log_outbox_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HoBomLogPayload.ProtoReflect.Descriptor instead.
func (*HoBomLogPayload) Descriptor() ([]byte, []int) {
	return file_log_outbox_v1_hobom_log_outbox_proto_rawDescGZIP(), []int{3}
}

func (x *HoBomLogPayload) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *HoBomLogPayload) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *HoBomLogPayload) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HoBomLogPayload) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HoBomLogPayload) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *HoBomLogPayload) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *HoBomLogPayload) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *HoBomLogPayload) GetPayload() *LogPayloadDetail {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *HoBomLogPayload) GetServiceType() string {
	if x != nil {
		return x.ServiceType
	}
	return ""
}

func (x *HoBomLogPayload) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LogPayloadDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         map[string]string      `protobuf:"bytes,1,rep,name=query,proto3" json:"query,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          map[string]string      `protobuf:"bytes,2,rep,name=body,proto3" json:"body,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogPayloadDetail) Reset() {
	*x = LogPayloadDetail{}
	mi := &file_log_outbox_v1_hobom_log_outbox_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogPayloadDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogPayloadDetail) ProtoMessage() {}

func (x *LogPayloadDetail) ProtoReflect() protoreflect.Message {
	mi := &file_log_outbox_v1_hobom_log_outbox_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogPayloadDetail.ProtoReflect.Descriptor instead.
func (*LogPayloadDetail) Descriptor() ([]byte, []int) {
	return file_log_outbox_v1_hobom_log_outbox_proto_rawDescGZIP(), []int{4}
}

func (x *LogPayloadDetail) GetQuery() map[string]string {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *LogPayloadDetail) GetBody() map[string]string {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *LogPayloadDetail) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *LogPayloadDetail) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_log_outbox_v1_hobom_log_outbox_proto protoreflect.FileDescriptor

const file_log_outbox_v1_hobom_log_outbox_proto_rawDesc = "" +
	"\n" +
	"$log/outbox/v1/hobom-log-outbox.proto\x12\n" +
	"outbox.log\"?\n" +
	"\aRequest\x12\x1c\n" +
	"\teventType\x18\x01 \x01(\tR\teventType\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"9\n" +
	"\bResponse\x12-\n" +
	"\x05items\x18\x01 \x03(\v2\x17.outbox.log.QueryResultR\x05items\"\xec\x02\n" +
	"\vQueryResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aeventId\x18\x02 \x01(\tR\aeventId\x12\x1c\n" +
	"\teventType\x18\x03 \x01(\tR\teventType\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"retryCount\x18\x05 \x01(\x05R\n" +
	"retryCount\x12\x16\n" +
	"\x06sentAt\x18\x06 \x01(\tR\x06sentAt\x12\x1a\n" +
	"\bfailedAt\x18\a \x01(\tR\bfailedAt\x12\x1c\n" +
	"\tlastError\x18\b \x01(\tR\tlastError\x12\x18\n" +
	"\aversion\x18\t \x01(\x05R\aversion\x12\x1c\n" +
	"\tcreatedAt\x18\n" +
	" \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\v \x01(\tR\tupdatedAt\x125\n" +
	"\apayload\x18\f \x01(\v2\x1b.outbox.log.HoBomLogPayloadR\apayload\"\xad\x02\n" +
	"\x0fHoBomLogPayload\x12\x18\n" +
	"\atraceId\x18\x01 \x01(\tR\atraceId\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x1e\n" +
	"\n" +
	"statusCode\x18\x05 \x01(\x05R\n" +
	"statusCode\x12\x12\n" +
	"\x04host\x18\x06 \x01(\tR\x04host\x12\x16\n" +
	"\x06userId\x18\a \x01(\tR\x06userId\x126\n" +
	"\apayload\x18\b \x01(\v2\x1c.outbox.log.LogPayloadDetailR\apayload\x12 \n" +
	"\vserviceType\x18\t \x01(\tR\vserviceType\x12\x18\n" +
	"\amessage\x18\n" +
	" \x01(\tR\amessage\"\x97\x03\n" +
	"\x10LogPayloadDetail\x12=\n" +
	"\x05query\x18\x01 \x03(\v2'.outbox.log.LogPayloadDetail.QueryEntryR\x05query\x12:\n" +
	"\x04body\x18\x02 \x03(\v2&.outbox.log.LogPayloadDetail.BodyEntryR\x04body\x12C\n" +
	"\aheaders\x18\x03 \x03(\v2).outbox.log.LogPayloadDetail.HeadersEntryR\aheaders\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x1a8\n" +
	"\n" +
	"QueryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a7\n" +
	"\tBodyEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012u\n" +
	"\x1cFindHoBomLogOutboxController\x12U\n" +
	"(FindLogOutboxByEventTypeAndStatusUseCase\x12\x13.outbox.log.Request\x1a\x14.outbox.log.ResponseBTZRgithub.com/HoBom-s/hobom-event-processor/infra/grpc/v1/hobom-log-outbox;hobomlogpbb\x06proto3"

var (
	file_log_outbox_v1_hobom_log_outbox_proto_rawDescOnce sync.Once
	file_log_outbox_v1_hobom_log_outbox_proto_rawDescData []byte
)

func file_log_outbox_v1_hobom_log_outbox_proto_rawDescGZIP() []byte {
	file_log_outbox_v1_hobom_log_outbox_proto_rawDescOnce.Do(func() {
		file_log_outbox_v1_hobom_log_outbox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_log_outbox_v1_hobom_log_outbox_proto_rawDesc), len(file_log_outbox_v1_hobom_log_outbox_proto_rawDesc)))
	})
	return file_log_outbox_v1_hobom_log_outbox_proto_rawDescData
}

var file_log_outbox_v1_hobom_log_outbox_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_log_outbox_v1_hobom_log_outbox_proto_goTypes = []any{
	(*Request)(nil),          // 0: outbox.log.Request
	(*Response)(nil),         // 1: outbox.log.Response
	(*QueryResult)(nil),      // 2: outbox.log.QueryResult
	(*HoBomLogPayload)(nil),  // 3: outbox.log.HoBomLogPayload
	(*LogPayloadDetail)(nil), // 4: outbox.log.LogPayloadDetail
	nil,                      // 5: outbox.log.LogPayloadDetail.QueryEntry
	nil,                      // 6: outbox.log.LogPayloadDetail.BodyEntry
	nil,                      // 7: outbox.log.LogPayloadDetail.HeadersEntry
}
var file_log_outbox_v1_hobom_log_outbox_proto_depIdxs = []int32{
	2, // 0: outbox.log.Response.items:type_name -> outbox.log.QueryResult
	3, // 1: outbox.log.QueryResult.payload:type_name -> outbox.log.HoBomLogPayload
	4, // 2: outbox.log.HoBomLogPayload.payload:type_name -> outbox.log.LogPayloadDetail
	5, // 3: outbox.log.LogPayloadDetail.query:type_name -> outbox.log.LogPayloadDetail.QueryEntry
	6, // 4: outbox.log.LogPayloadDetail.body:type_name -> outbox.log.LogPayloadDetail.BodyEntry
	7, // 5: outbox.log.LogPayloadDetail.headers:type_name -> outbox.log.LogPayloadDetail.HeadersEntry
	0, // 6: outbox.log.FindHoBomLogOutboxController.FindLogOutboxByEventTypeAndStatusUseCase:input_type -> outbox.log.Request
	1, // 7: outbox.log.FindHoBomLogOutboxController.FindLogOutboxByEventTypeAndStatusUseCase:output_type -> outbox.log.Response
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_log_outbox_v1_hobom_log_outbox_proto_init() }
func file_log_outbox_v1_hobom_log_outbox_proto_init() {
	if File_log_outbox_v1_hobom_log_outbox_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_log_outbox_v1_hobom_log_outbox_proto_rawDesc), len(file_log_outbox_v1_hobom_log_outbox_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_log_outbox_v1_hobom_log_outbox_proto_goTypes,
		DependencyIndexes: file_log_outbox_v1_hobom_log_outbox_proto_depIdxs,
		MessageInfos:      file_log_outbox_v1_hobom_log_outbox_proto_msgTypes,
	}.Build()
	File_log_outbox_v1_hobom_log_outbox_proto = out.File
	file_log_outbox_v1_hobom_log_outbox_proto_goTypes = nil
	file_log_outbox_v1_hobom_log_outbox_proto_depIdxs = nil
}
