// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: log/outbox/v1/hobom-log-outbox.proto

package hobomlogpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FindHoBomLogOutboxController_FindLogOutboxByEventTypeAndStatusUseCase_FullMethodName = "/outbox.log.FindHoBomLogOutboxController/FindLogOutboxByEventTypeAndStatusUseCase"
)

// FindHoBomLogOutboxControllerClient is the client API for FindHoBomLogOutboxController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FindHoBomLogOutboxControllerClient interface {
	FindLogOutboxByEventTypeAndStatusUseCase(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type findHoBomLogOutboxControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewFindHoBomLogOutboxControllerClient(cc grpc.ClientConnInterface) FindHoBomLogOutboxControllerClient {
	return &findHoBomLogOutboxControllerClient{cc}
}

func (c *findHoBomLogOutboxControllerClient) FindLogOutboxByEventTypeAndStatusUseCase(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, FindHoBomLogOutboxController_FindLogOutboxByEventTypeAndStatusUseCase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FindHoBomLogOutboxControllerServer is the server API for FindHoBomLogOutboxController service.
// All implementations must embed UnimplementedFindHoBomLogOutboxControllerServer
// for forward compatibility.
type FindHoBomLogOutboxControllerServer interface {
	FindLogOutboxByEventTypeAndStatusUseCase(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedFindHoBomLogOutboxControllerServer()
}

// UnimplementedFindHoBomLogOutboxControllerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFindHoBomLogOutboxControllerServer struct{}

func (UnimplementedFindHoBomLogOutboxControllerServer) FindLogOutboxByEventTypeAndStatusUseCase(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindLogOutboxByEventTypeAndStatusUseCase not implemented")
}
func (UnimplementedFindHoBomLogOutboxControllerServer) mustEmbedUnimplementedFindHoBomLogOutboxControllerServer() {
}
func (UnimplementedFindHoBomLogOutboxControllerServer) testEmbeddedByValue() {}

// UnsafeFindHoBomLogOutboxControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FindHoBomLogOutboxControllerServer will
// result in compilation errors.
type UnsafeFindHoBomLogOutboxControllerServer interface {
	mustEmbedUnimplementedFindHoBomLogOutboxControllerServer()
}

func RegisterFindHoBomLogOutboxControllerServer(s grpc.ServiceRegistrar, srv FindHoBomLogOutboxControllerServer) {
	// If the following call pancis, it indicates UnimplementedFindHoBomLogOutboxControllerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FindHoBomLogOutboxController_ServiceDesc, srv)
}

func _FindHoBomLogOutboxController_FindLogOutboxByEventTypeAndStatusUseCase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FindHoBomLogOutboxControllerServer).FindLogOutboxByEventTypeAndStatusUseCase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FindHoBomLogOutboxController_FindLogOutboxByEventTypeAndStatusUseCase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FindHoBomLogOutboxControllerServer).FindLogOutboxByEventTypeAndStatusUseCase(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// FindHoBomLogOutboxController_ServiceDesc is the grpc.ServiceDesc for FindHoBomLogOutboxController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FindHoBomLogOutboxController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "outbox.log.FindHoBomLogOutboxController",
	HandlerType: (*FindHoBomLogOutboxControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindLogOutboxByEventTypeAndStatusUseCase",
			Handler:    _FindHoBomLogOutboxController_FindLogOutboxByEventTypeAndStatusUseCase_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "log/outbox/v1/hobom-log-outbox.proto",
}
