// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: law/v1/save-study-material.proto

package lawpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SaveStudyMaterialController_SaveStudyMaterial_FullMethodName = "/law.SaveStudyMaterialController/SaveStudyMaterial"
)

// SaveStudyMaterialControllerClient is the client API for SaveStudyMaterialController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SaveStudyMaterialControllerClient interface {
	SaveStudyMaterial(ctx context.Context, in *SaveStudyMaterialRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type saveStudyMaterialControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewSaveStudyMaterialControllerClient(cc grpc.ClientConnInterface) SaveStudyMaterialControllerClient {
	return &saveStudyMaterialControllerClient{cc}
}

func (c *saveStudyMaterialControllerClient) SaveStudyMaterial(ctx context.Context, in *SaveStudyMaterialRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SaveStudyMaterialController_SaveStudyMaterial_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SaveStudyMaterialControllerServer is the server API for SaveStudyMaterialController service.
// All implementations must embed UnimplementedSaveStudyMaterialControllerServer
// for forward compatibility.
type SaveStudyMaterialControllerServer interface {
	SaveStudyMaterial(context.Context, *SaveStudyMaterialRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedSaveStudyMaterialControllerServer()
}

// UnimplementedSaveStudyMaterialControllerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSaveStudyMaterialControllerServer struct{}

func (UnimplementedSaveStudyMaterialControllerServer) SaveStudyMaterial(context.Context, *SaveStudyMaterialRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveStudyMaterial not implemented")
}
func (UnimplementedSaveStudyMaterialControllerServer) mustEmbedUnimplementedSaveStudyMaterialControllerServer() {
}
func (UnimplementedSaveStudyMaterialControllerServer) testEmbeddedByValue() {}

// UnsafeSaveStudyMaterialControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SaveStudyMaterialControllerServer will
// result in compilation errors.
type UnsafeSaveStudyMaterialControllerServer interface {
	mustEmbedUnimplementedSaveStudyMaterialControllerServer()
}

func RegisterSaveStudyMaterialControllerServer(s grpc.ServiceRegistrar, srv SaveStudyMaterialControllerServer) {
	// If the following call pancis, it indicates UnimplementedSaveStudyMaterialControllerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SaveStudyMaterialController_ServiceDesc, srv)
}

func _SaveStudyMaterialController_SaveStudyMaterial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveStudyMaterialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SaveStudyMaterialControllerServer).SaveStudyMaterial(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SaveStudyMaterialController_SaveStudyMaterial_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SaveStudyMaterialControllerServer).SaveStudyMaterial(ctx, req.(*SaveStudyMaterialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SaveStudyMaterialController_ServiceDesc is the grpc.ServiceDesc for SaveStudyMaterialController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SaveStudyMaterialController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "law.SaveStudyMaterialController",
	HandlerType: (*SaveStudyMaterialControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveStudyMaterial",
			Handler:    _SaveStudyMaterialController_SaveStudyMaterial_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "law/v1/save-study-material.proto",
}
