// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: law/v1/save-study-material.proto

package lawpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Quiz struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Question      string                 `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	Answer        string                 `protobuf:"bytes,3,opt,name=answer,proto3" json:"answer,omitempty"`
	Explanation   string                 `protobuf:"bytes,4,opt,name=explanation,proto3" json:"explanation,omitempty"`
	Choices       []string               `protobuf:"bytes,5,rep,name=choices,proto3" json:"choices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Quiz) Reset() {
	*x = Quiz{}
	mi := &file_law_v1_save_study_material_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quiz) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quiz) ProtoMessage() {}

func (x *Quiz) ProtoReflect() protoreflect.Message {
	mi := &file_law_v1_save_study_material_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quiz.ProtoReflect.Descriptor instead.
func (*Quiz) Descriptor() ([]byte, []int) {
	return file_law_v1_save_study_material_proto_rawDescGZIP(), []int{0}
}

func (x *Quiz) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Quiz) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *Quiz) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *Quiz) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

func (x *Quiz) GetChoices() []string {
	if x != nil {
		return x.Choices
	}
	return nil
}

type SaveStudyMaterialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DiffId        string                 `protobuf:"bytes,1,opt,name=diffId,proto3" json:"diffId,omitempty"`
	Summary       string                 `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	KeyPoints     []string               `protobuf:"bytes,3,rep,name=keyPoints,proto3" json:"keyPoints,omitempty"`
	Quizzes       []*Quiz                `protobuf:"bytes,4,rep,name=quizzes,proto3" json:"quizzes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveStudyMaterialRequest) Reset() {
	*x = SaveStudyMaterialRequest{}
	mi := &file_law_v1_save_study_material_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveStudyMaterialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveStudyMaterialRequest) ProtoMessage() {}

func (x *SaveStudyMaterialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_law_v1_save_study_material_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveStudyMaterialRequest.ProtoReflect.Descriptor instead.
func (*SaveStudyMaterialRequest) Descriptor() ([]byte, []int) {
	return file_law_v1_save_study_material_proto_rawDescGZIP(), []int{1}
}

func (x *SaveStudyMaterialRequest) GetDiffId() string {
	if x != nil {
		return x.DiffId
	}
	return ""
}

func (x *SaveStudyMaterialRequest) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *SaveStudyMaterialRequest) GetKeyPoints() []string {
	if x != nil {
		return x.KeyPoints
	}
	return nil
}

func (x *SaveStudyMaterialRequest) GetQuizzes() []*Quiz {
	if x != nil {
		return x.Quizzes
	}
	return nil
}

var File_law_v1_save_study_material_proto protoreflect.FileDescriptor

const file_law_v1_save_study_material_proto_rawDesc = "" +
	"\n" +
	" law/v1/save-study-material.proto\x12\x03law\x1a\x1bgoogle/protobuf/empty.proto\"\x8a\x01\n" +
	"\x04Quiz\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1a\n" +
	"\bquestion\x18\x02 \x01(\tR\bquestion\x12\x16\n" +
	"\x06answer\x18\x03 \x01(\tR\x06answer\x12 \n" +
	"\vexplanation\x18\x04 \x01(\tR\vexplanation\x12\x18\n" +
	"\achoices\x18\x05 \x03(\tR\achoices\"\x8f\x01\n" +
	"\x18SaveStudyMaterialRequest\x12\x16\n" +
	"\x06diffId\x18\x01 \x01(\tR\x06diffId\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x12\x1c\n" +
	"\tkeyPoints\x18\x03 \x03(\tR\tkeyPoints\x12#\n" +
	"\aquizzes\x18\x04 \x03(\v2\t.law.QuizR\aquizzes2i\n" +
	"\x1bSaveStudyMaterialController\x12J\n" +
	"\x11SaveStudyMaterial\x12\x1d.law.SaveStudyMaterialRequest\x1a\x16.google.protobuf.EmptyBBZ@github.com/HoBom-s/hobom-event-processor/infra/grpc/v1/law;lawpbb\x06proto3"

var (
	file_law_v1_save_study_material_proto_rawDescOnce sync.Once
	file_law_v1_save_study_material_proto_rawDescData []byte
)

func file_law_v1_save_study_material_proto_rawDescGZIP() []byte {
	file_law_v1_save_study_material_proto_rawDescOnce.Do(func() {
		file_law_v1_save_study_material_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_law_v1_save_study_material_proto_rawDesc), len(file_law_v1_save_study_material_proto_rawDesc)))
	})
	return file_law_v1_save_study_material_proto_rawDescData
}

var file_law_v1_save_study_material_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_law_v1_save_study_material_proto_goTypes = []any{
	(*Quiz)(nil),                     // 0: law.Quiz
	(*SaveStudyMaterialRequest)(nil), // 1: law.SaveStudyMaterialRequest
	(*emptypb.Empty)(nil),            // 2: google.protobuf.Empty
}
var file_law_v1_save_study_material_proto_depIdxs = []int32{
	0, // 0: law.SaveStudyMaterialRequest.quizzes:type_name -> law.Quiz
	1, // 1: law.SaveStudyMaterialController.SaveStudyMaterial:input_type -> law.SaveStudyMaterialRequest
	2, // 2: law.SaveStudyMaterialController.SaveStudyMaterial:output_type -> google.protobuf.Empty
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_law_v1_save_study_material_proto_init() }
func file_law_v1_save_study_material_proto_init() {
	if File_law_v1_save_study_material_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_law_v1_save_study_material_proto_rawDesc), len(file_law_v1_save_study_material_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_law_v1_save_study_material_proto_goTypes,
		DependencyIndexes: file_law_v1_save_study_material_proto_depIdxs,
		MessageInfos:      file_law_v1_save_study_material_proto_msgTypes,
	}.Build()
	File_law_v1_save_study_material_proto = out.File
	file_law_v1_save_study_material_proto_goTypes = nil
	file_law_v1_save_study_material_proto_depIdxs = nil
}
