// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: menu/outbox/v1/hobom-menu-outbox.proto

package hobommenupb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FindTodayMenuOutboxController_FindOutboxByEventTypeAndStatusUseCase_FullMethodName = "/outbox.FindTodayMenuOutboxController/FindOutboxByEventTypeAndStatusUseCase"
)

// FindTodayMenuOutboxControllerClient is the client API for FindTodayMenuOutboxController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FindTodayMenuOutboxControllerClient interface {
	FindOutboxByEventTypeAndStatusUseCase(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type findTodayMenuOutboxControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewFindTodayMenuOutboxControllerClient(cc grpc.ClientConnInterface) FindTodayMenuOutboxControllerClient {
	return &findTodayMenuOutboxControllerClient{cc}
}

func (c *findTodayMenuOutboxControllerClient) FindOutboxByEventTypeAndStatusUseCase(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, FindTodayMenuOutboxController_FindOutboxByEventTypeAndStatusUseCase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FindTodayMenuOutboxControllerServer is the server API for FindTodayMenuOutboxController service.
// All implementations must embed UnimplementedFindTodayMenuOutboxControllerServer
// for forward compatibility.
type FindTodayMenuOutboxControllerServer interface {
	FindOutboxByEventTypeAndStatusUseCase(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedFindTodayMenuOutboxControllerServer()
}

// UnimplementedFindTodayMenuOutboxControllerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFindTodayMenuOutboxControllerServer struct{}

func (UnimplementedFindTodayMenuOutboxControllerServer) FindOutboxByEventTypeAndStatusUseCase(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindOutboxByEventTypeAndStatusUseCase not implemented")
}
func (UnimplementedFindTodayMenuOutboxControllerServer) mustEmbedUnimplementedFindTodayMenuOutboxControllerServer() {
}
func (UnimplementedFindTodayMenuOutboxControllerServer) testEmbeddedByValue() {}

// UnsafeFindTodayMenuOutboxControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FindTodayMenuOutboxControllerServer will
// result in compilation errors.
type UnsafeFindTodayMenuOutboxControllerServer interface {
	mustEmbedUnimplementedFindTodayMenuOutboxControllerServer()
}

func RegisterFindTodayMenuOutboxControllerServer(s grpc.ServiceRegistrar, srv FindTodayMenuOutboxControllerServer) {
	// If the following call pancis, it indicates UnimplementedFindTodayMenuOutboxControllerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FindTodayMenuOutboxController_ServiceDesc, srv)
}

func _FindTodayMenuOutboxController_FindOutboxByEventTypeAndStatusUseCase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FindTodayMenuOutboxControllerServer).FindOutboxByEventTypeAndStatusUseCase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FindTodayMenuOutboxController_FindOutboxByEventTypeAndStatusUseCase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FindTodayMenuOutboxControllerServer).FindOutboxByEventTypeAndStatusUseCase(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// FindTodayMenuOutboxController_ServiceDesc is the grpc.ServiceDesc for FindTodayMenuOutboxController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FindTodayMenuOutboxController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "outbox.FindTodayMenuOutboxController",
	HandlerType: (*FindTodayMenuOutboxControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindOutboxByEventTypeAndStatusUseCase",
			Handler:    _FindTodayMenuOutboxController_FindOutboxByEventTypeAndStatusUseCase_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "menu/outbox/v1/hobom-menu-outbox.proto",
}
