// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: menu/outbox/v1/hobom-menu-outbox.proto

package hobommenupb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=eventType,proto3" json:"eventType,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_menu_outbox_v1_hobom_menu_outbox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_menu_outbox_v1_hobom_menu_outbox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_menu_outbox_v1_hobom_menu_outbox_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *Request) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*QueryResult         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_menu_outbox_v1_hobom_menu_outbox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_menu_outbox_v1_hobom_menu_outbox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_menu_outbox_v1_hobom_menu_outbox_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetItems() []*QueryResult {
	if x != nil {
		return x.Items
	}
	return nil
}

type QueryResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=eventId,proto3" json:"eventId,omitempty"`
	EventType     string                 `protobuf:"bytes,3,opt,name=eventType,proto3" json:"eventType,omitempty"`
	Payload       *TodayMenuPayload      `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	RetryCount    int32                  `protobuf:"varint,6,opt,name=retryCount,proto3" json:"retryCount,omitempty"`
	SentAt        string                 `protobuf:"bytes,7,opt,name=sentAt,proto3" json:"sentAt,omitempty"`
	FailedAt      string                 `protobuf:"bytes,8,opt,name=failedAt,proto3" json:"failedAt,omitempty"`
	LastError     string                 `protobuf:"bytes,9,opt,name=lastError,proto3" json:"lastError,omitempty"`
	Version       int32                  `protobuf:"varint,10,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,11,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,12,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResult) Reset() {
	*x = QueryResult{}
	mi := &file_menu_outbox_v1_hobom_menu_outbox_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResult) ProtoMessage() {}

func (x *QueryResult) ProtoReflect() protoreflect.Message {
	mi := &file_menu_outbox_v1_hobom_menu_outbox_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResult.ProtoReflect.Descriptor instead.
func (*QueryResult) Descriptor() ([]byte, []int) {
	return file_menu_outbox_v1_hobom_menu_outbox_proto_rawDescGZIP(), []int{2}
}

func (x *QueryResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QueryResult) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *QueryResult) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *QueryResult) GetPayload() *TodayMenuPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *QueryResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *QueryResult) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *QueryResult) GetSentAt() string {
	if x != nil {
		return x.SentAt
	}
	return ""
}

func (x *QueryResult) GetFailedAt() string {
	if x != nil {
		return x.FailedAt
	}
	return ""
}

func (x *QueryResult) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *QueryResult) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *QueryResult) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *QueryResult) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type TodayMenuPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TodayMenuId   string                 `protobuf:"bytes,1,opt,name=todayMenuId,proto3" json:"todayMenuId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TodayMenuPayload) Reset() {
	*x = TodayMenuPayload{}
	mi := &file_menu_outbox_v1_hobom_menu_outbox_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TodayMenuPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TodayMenuPayload) ProtoMessage() {}

func (x *TodayMenuPayload) ProtoReflect() protoreflect.Message {
	mi := &file_menu_outbox_v1_hobom_menu_outbox_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TodayMenuPayload.ProtoReflect.Descriptor instead.
func (*TodayMenuPayload) Descriptor() ([]byte, []int) {
	return file_menu_outbox_v1_hobom_menu_outbox_proto_rawDescGZIP(), []int{3}
}

func (x *TodayMenuPayload) GetTodayMenuId() string {
	if x != nil {
		return x.TodayMenuId
	}
	return ""
}

func (x *TodayMenuPayload) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_menu_outbox_v1_hobom_menu_outbox_proto protoreflect.FileDescriptor

const file_menu_outbox_v1_hobom_menu_outbox_proto_rawDesc = "" +
	"\n" +
	"&menu/outbox/v1/hobom-menu-outbox.proto\x12\x06outbox\"?\n" +
	"\aRequest\x12\x1c\n" +
	"\teventType\x18\x01 \x01(\tR\teventType\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"5\n" +
	"\bResponse\x12)\n" +
	"\x05items\x18\x01 \x03(\v2\x13.outbox.QueryResultR\x05items\"\xe9\x02\n" +
	"\vQueryResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aeventId\x18\x02 \x01(\tR\aeventId\x12\x1c\n" +
	"\teventType\x18\x03 \x01(\tR\teventType\x122\n" +
	"\apayload\x18\x04 \x01(\v2\x18.outbox.TodayMenuPayloadR\apayload\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"retryCount\x18\x06 \x01(\x05R\n" +
	"retryCount\x12\x16\n" +
	"\x06sentAt\x18\a \x01(\tR\x06sentAt\x12\x1a\n" +
	"\bfailedAt\x18\b \x01(\tR\bfailedAt\x12\x1c\n" +
	"\tlastError\x18\t \x01(\tR\tlastError\x12\x18\n" +
	"\aversion\x18\n" +
	" \x01(\x05R\aversion\x12\x1c\n" +
	"\tcreatedAt\x18\v \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\f \x01(\tR\tupdatedAt\"H\n" +
	"\x10TodayMenuPayload\x12 \n" +
	"\vtodayMenuId\x18\x01 \x01(\tR\vtodayMenuId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name2k\n" +
	"\x1dFindTodayMenuOutboxController\x12J\n" +
	"%FindOutboxByEventTypeAndStatusUseCase\x12\x0f.outbox.Request\x1a\x10.outbox.ResponseBVZTgithub.com/HoBom-s/hobom-event-processor/infra/grpc/v1/hobom-menu-outbox;hobommenupbb\x06proto3"

var (
	file_menu_outbox_v1_hobom_menu_outbox_proto_rawDescOnce sync.Once
	file_menu_outbox_v1_hobom_menu_outbox_proto_rawDescData []byte
)

func file_menu_outbox_v1_hobom_menu_outbox_proto_rawDescGZIP() []byte {
	file_menu_outbox_v1_hobom_menu_outbox_proto_rawDescOnce.Do(func() {
		file_menu_outbox_v1_hobom_menu_outbox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_menu_outbox_v1_hobom_menu_outbox_proto_rawDesc), len(file_menu_outbox_v1_hobom_menu_outbox_proto_rawDesc)))
	})
	return file_menu_outbox_v1_hobom_menu_outbox_proto_rawDescData
}

var file_menu_outbox_v1_hobom_menu_outbox_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_menu_outbox_v1_hobom_menu_outbox_proto_goTypes = []any{
	(*Request)(nil),          // 0: outbox.Request
	(*Response)(nil),         // 1: outbox.Response
	(*QueryResult)(nil),      // 2: outbox.QueryResult
	(*TodayMenuPayload)(nil), // 3: outbox.TodayMenuPayload
}
var file_menu_outbox_v1_hobom_menu_outbox_proto_depIdxs = []int32{
	2, // 0: outbox.Response.items:type_name -> outbox.QueryResult
	3, // 1: outbox.QueryResult.payload:type_name -> outbox.TodayMenuPayload
	0, // 2: outbox.FindTodayMenuOutboxController.FindOutboxByEventTypeAndStatusUseCase:input_type -> outbox.Request
	1, // 3: outbox.FindTodayMenuOutboxController.FindOutboxByEventTypeAndStatusUseCase:output_type -> outbox.Response
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_menu_outbox_v1_hobom_menu_outbox_proto_init() }
func file_menu_outbox_v1_hobom_menu_outbox_proto_init() {
	if File_menu_outbox_v1_hobom_menu_outbox_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_menu_outbox_v1_hobom_menu_outbox_proto_rawDesc), len(file_menu_outbox_v1_hobom_menu_outbox_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_menu_outbox_v1_hobom_menu_outbox_proto_goTypes,
		DependencyIndexes: file_menu_outbox_v1_hobom_menu_outbox_proto_depIdxs,
		MessageInfos:      file_menu_outbox_v1_hobom_menu_outbox_proto_msgTypes,
	}.Build()
	File_menu_outbox_v1_hobom_menu_outbox_proto = out.File
	file_menu_outbox_v1_hobom_menu_outbox_proto_goTypes = nil
	file_menu_outbox_v1_hobom_menu_outbox_proto_depIdxs = nil
}
