// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: menu/outbox/v1/patch-hobom-menu-outbox.proto

package hobommenupb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PatchOutboxController_PatchOutboxMarkAsSentUseCase_FullMethodName   = "/outbox.menu.PatchOutboxController/PatchOutboxMarkAsSentUseCase"
	PatchOutboxController_PatchOutboxMarkAsFailedUseCase_FullMethodName = "/outbox.menu.PatchOutboxController/PatchOutboxMarkAsFailedUseCase"
)

// PatchOutboxControllerClient is the client API for PatchOutboxController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PatchOutboxControllerClient interface {
	PatchOutboxMarkAsSentUseCase(ctx context.Context, in *MarkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	PatchOutboxMarkAsFailedUseCase(ctx context.Context, in *MarkFailedRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type patchOutboxControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewPatchOutboxControllerClient(cc grpc.ClientConnInterface) PatchOutboxControllerClient {
	return &patchOutboxControllerClient{cc}
}

func (c *patchOutboxControllerClient) PatchOutboxMarkAsSentUseCase(ctx context.Context, in *MarkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PatchOutboxController_PatchOutboxMarkAsSentUseCase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *patchOutboxControllerClient) PatchOutboxMarkAsFailedUseCase(ctx context.Context, in *MarkFailedRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PatchOutboxController_PatchOutboxMarkAsFailedUseCase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PatchOutboxControllerServer is the server API for PatchOutboxController service.
// All implementations must embed UnimplementedPatchOutboxControllerServer
// for forward compatibility.
type PatchOutboxControllerServer interface {
	PatchOutboxMarkAsSentUseCase(context.Context, *MarkRequest) (*emptypb.Empty, error)
	PatchOutboxMarkAsFailedUseCase(context.Context, *MarkFailedRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedPatchOutboxControllerServer()
}

// UnimplementedPatchOutboxControllerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPatchOutboxControllerServer struct{}

func (UnimplementedPatchOutboxControllerServer) PatchOutboxMarkAsSentUseCase(context.Context, *MarkRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PatchOutboxMarkAsSentUseCase not implemented")
}
func (UnimplementedPatchOutboxControllerServer) PatchOutboxMarkAsFailedUseCase(context.Context, *MarkFailedRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PatchOutboxMarkAsFailedUseCase not implemented")
}
func (UnimplementedPatchOutboxControllerServer) mustEmbedUnimplementedPatchOutboxControllerServer() {}
func (UnimplementedPatchOutboxControllerServer) testEmbeddedByValue()                               {}

// UnsafePatchOutboxControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PatchOutboxControllerServer will
// result in compilation errors.
type UnsafePatchOutboxControllerServer interface {
	mustEmbedUnimplementedPatchOutboxControllerServer()
}

func RegisterPatchOutboxControllerServer(s grpc.ServiceRegistrar, srv PatchOutboxControllerServer) {
	// If the following call pancis, it indicates UnimplementedPatchOutboxControllerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PatchOutboxController_ServiceDesc, srv)
}

func _PatchOutboxController_PatchOutboxMarkAsSentUseCase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PatchOutboxControllerServer).PatchOutboxMarkAsSentUseCase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PatchOutboxController_PatchOutboxMarkAsSentUseCase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PatchOutboxControllerServer).PatchOutboxMarkAsSentUseCase(ctx, req.(*MarkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PatchOutboxController_PatchOutboxMarkAsFailedUseCase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkFailedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PatchOutboxControllerServer).PatchOutboxMarkAsFailedUseCase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PatchOutboxController_PatchOutboxMarkAsFailedUseCase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PatchOutboxControllerServer).PatchOutboxMarkAsFailedUseCase(ctx, req.(*MarkFailedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PatchOutboxController_ServiceDesc is the grpc.ServiceDesc for PatchOutboxController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PatchOutboxController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "outbox.menu.PatchOutboxController",
	HandlerType: (*PatchOutboxControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PatchOutboxMarkAsSentUseCase",
			Handler:    _PatchOutboxController_PatchOutboxMarkAsSentUseCase_Handler,
		},
		{
			MethodName: "PatchOutboxMarkAsFailedUseCase",
			Handler:    _PatchOutboxController_PatchOutboxMarkAsFailedUseCase_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "menu/outbox/v1/patch-hobom-menu-outbox.proto",
}
