// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        (unknown)
// source: law/outbox/v1/find-hobom-law-outbox.proto

package hobomlawpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventType string `protobuf:"bytes,1,opt,name=eventType,proto3" json:"eventType,omitempty"`
	Status    string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_law_outbox_v1_find_hobom_law_outbox_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_law_outbox_v1_find_hobom_law_outbox_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_law_outbox_v1_find_hobom_law_outbox_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *Request) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*QueryResult `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_law_outbox_v1_find_hobom_law_outbox_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_law_outbox_v1_find_hobom_law_outbox_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_law_outbox_v1_find_hobom_law_outbox_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetItems() []*QueryResult {
	if x != nil {
		return x.Items
	}
	return nil
}

type QueryResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EventId    string             `protobuf:"bytes,2,opt,name=eventId,proto3" json:"eventId,omitempty"`
	EventType  string             `protobuf:"bytes,3,opt,name=eventType,proto3" json:"eventType,omitempty"`
	Payload    *LawChangedPayload `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Status     string             `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	RetryCount int32              `protobuf:"varint,6,opt,name=retryCount,proto3" json:"retryCount,omitempty"`
	SentAt     string             `protobuf:"bytes,7,opt,name=sentAt,proto3" json:"sentAt,omitempty"`
	FailedAt   string             `protobuf:"bytes,8,opt,name=failedAt,proto3" json:"failedAt,omitempty"`
	LastError  string             `protobuf:"bytes,9,opt,name=lastError,proto3" json:"lastError,omitempty"`
	Version    int32              `protobuf:"varint,10,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt  string             `protobuf:"bytes,11,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt  string             `protobuf:"bytes,12,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
}

func (x *QueryResult) Reset() {
	*x = QueryResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_law_outbox_v1_find_hobom_law_outbox_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResult) ProtoMessage() {}

func (x *QueryResult) ProtoReflect() protoreflect.Message {
	mi := &file_law_outbox_v1_find_hobom_law_outbox_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResult.ProtoReflect.Descriptor instead.
func (*QueryResult) Descriptor() ([]byte, []int) {
	return file_law_outbox_v1_find_hobom_law_outbox_proto_rawDescGZIP(), []int{2}
}

func (x *QueryResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QueryResult) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *QueryResult) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *QueryResult) GetPayload() *LawChangedPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *QueryResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *QueryResult) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *QueryResult) GetSentAt() string {
	if x != nil {
		return x.SentAt
	}
	return ""
}

func (x *QueryResult) GetFailedAt() string {
	if x != nil {
		return x.FailedAt
	}
	return ""
}

func (x *QueryResult) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *QueryResult) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *QueryResult) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *QueryResult) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type LawChangedPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DiffId  string              `protobuf:"bytes,1,opt,name=diffId,proto3" json:"diffId,omitempty"`
	Changes []*LawArticleChange `protobuf:"bytes,2,rep,name=changes,proto3" json:"changes,omitempty"`
}

func (x *LawChangedPayload) Reset() {
	*x = LawChangedPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_law_outbox_v1_find_hobom_law_outbox_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LawChangedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LawChangedPayload) ProtoMessage() {}

func (x *LawChangedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_law_outbox_v1_find_hobom_law_outbox_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LawChangedPayload.ProtoReflect.Descriptor instead.
func (*LawChangedPayload) Descriptor() ([]byte, []int) {
	return file_law_outbox_v1_find_hobom_law_outbox_proto_rawDescGZIP(), []int{3}
}

func (x *LawChangedPayload) GetDiffId() string {
	if x != nil {
		return x.DiffId
	}
	return ""
}

func (x *LawChangedPayload) GetChanges() []*LawArticleChange {
	if x != nil {
		return x.Changes
	}
	return nil
}

type LawArticleChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ArticleNo  string `protobuf:"bytes,1,opt,name=articleNo,proto3" json:"articleNo,omitempty"`
	ChangeType string `protobuf:"bytes,2,opt,name=changeType,proto3" json:"changeType,omitempty"`
	Before     string `protobuf:"bytes,3,opt,name=before,proto3" json:"before,omitempty"`
	After      string `protobuf:"bytes,4,opt,name=after,proto3" json:"after,omitempty"`
}

func (x *LawArticleChange) Reset() {
	*x = LawArticleChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_law_outbox_v1_find_hobom_law_outbox_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LawArticleChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LawArticleChange) ProtoMessage() {}

func (x *LawArticleChange) ProtoReflect() protoreflect.Message {
	mi := &file_law_outbox_v1_find_hobom_law_outbox_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LawArticleChange.ProtoReflect.Descriptor instead.
func (*LawArticleChange) Descriptor() ([]byte, []int) {
	return file_law_outbox_v1_find_hobom_law_outbox_proto_rawDescGZIP(), []int{4}
}

func (x *LawArticleChange) GetArticleNo() string {
	if x != nil {
		return x.ArticleNo
	}
	return ""
}

func (x *LawArticleChange) GetChangeType() string {
	if x != nil {
		return x.ChangeType
	}
	return ""
}

func (x *LawArticleChange) GetBefore() string {
	if x != nil {
		return x.Before
	}
	return ""
}

func (x *LawArticleChange) GetAfter() string {
	if x != nil {
		return x.After
	}
	return ""
}

var File_law_outbox_v1_find_hobom_law_outbox_proto protoreflect.FileDescriptor

var file_law_outbox_v1_find_hobom_law_outbox_proto_rawDesc = []byte{
	0x0a, 0x29, 0x6c, 0x61, 0x77, 0x2f, 0x6f, 0x75, 0x74, 0x62, 0x6f, 0x78, 0x2f, 0x76, 0x31, 0x2f,
	0x66, 0x69, 0x6e, 0x64, 0x2d, 0x68, 0x6f, 0x62, 0x6f, 0x6d, 0x2d, 0x6c, 0x61, 0x77, 0x2d, 0x6f,
	0x75, 0x74, 0x62, 0x6f, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6f, 0x75, 0x74,
	0x62, 0x6f, 0x78, 0x2e, 0x6c, 0x61, 0x77, 0x22, 0x3f, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x39, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6f, 0x75, 0x74, 0x62, 0x6f, 0x78, 0x2e, 0x6c, 0x61, 0x77,
	0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x05, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x22, 0xee, 0x02, 0x0a, 0x0b, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1c, 0x0a,
	0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x37, 0x0a, 0x07, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6f,
	0x75, 0x74, 0x62, 0x6f, 0x78, 0x2e, 0x6c, 0x61, 0x77, 0x2e, 0x4c, 0x61, 0x77, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x64, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x07, 0x70, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1e, 0x0a, 0x0a,
	0x72, 0x65, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0a, 0x72, 0x65, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x65, 0x6e, 0x74, 0x41, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65,
	0x6e, 0x74, 0x41, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x41, 0x74,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x41, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x18,
	0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x22, 0x63, 0x0a, 0x11, 0x4c, 0x61, 0x77, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x64, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x69, 0x66,
	0x66, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x69, 0x66, 0x66, 0x49,
	0x64, 0x12, 0x36, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6f, 0x75, 0x74, 0x62, 0x6f, 0x78, 0x2e, 0x6c, 0x61, 0x77, 0x2e,
	0x4c, 0x61, 0x77, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x22, 0x7e, 0x0a, 0x10, 0x4c, 0x61, 0x77,
	0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x4e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x4e, 0x6f, 0x12, 0x1e, 0x0a, 0x0a, 0x63,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x62,
	0x65, 0x66, 0x6f, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x65, 0x66,
	0x6f, 0x72, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x66, 0x74, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x61, 0x66, 0x74, 0x65, 0x72, 0x32, 0x72, 0x0a, 0x1c, 0x46, 0x69, 0x6e,
	0x64, 0x48, 0x6f, 0x42, 0x6f, 0x6d, 0x4c, 0x61, 0x77, 0x4f, 0x75, 0x74, 0x62, 0x6f, 0x78, 0x43,
	0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x52, 0x0a, 0x25, 0x46, 0x69, 0x6e,
	0x64, 0x4f, 0x75, 0x74, 0x62, 0x6f, 0x78, 0x42, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x41, 0x6e, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x55, 0x73, 0x65, 0x43, 0x61,
	0x73, 0x65, 0x12, 0x13, 0x2e, 0x6f, 0x75, 0x74, 0x62, 0x6f, 0x78, 0x2e, 0x6c, 0x61, 0x77, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x6f, 0x75, 0x74, 0x62, 0x6f, 0x78,
	0x2e, 0x6c, 0x61, 0x77, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x54, 0x5a,
	0x52, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x48, 0x6f, 0x42, 0x6f,
	0x6d, 0x2d, 0x73, 0x2f, 0x68, 0x6f, 0x62, 0x6f, 0x6d, 0x2d, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2d,
	0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2f, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x2f,
	0x67, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x31, 0x2f, 0x68, 0x6f, 0x62, 0x6f, 0x6d, 0x2d, 0x6c, 0x61,
	0x77, 0x2d, 0x6f, 0x75, 0x74, 0x62, 0x6f, 0x78, 0x3b, 0x68, 0x6f, 0x62, 0x6f, 0x6d, 0x6c, 0x61,
	0x77, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_law_outbox_v1_find_hobom_law_outbox_proto_rawDescOnce sync.Once
	file_law_outbox_v1_find_hobom_law_outbox_proto_rawDescData = file_law_outbox_v1_find_hobom_law_outbox_proto_rawDesc
)

func file_law_outbox_v1_find_hobom_law_outbox_proto_rawDescGZIP() []byte {
	file_law_outbox_v1_find_hobom_law_outbox_proto_rawDescOnce.Do(func() {
		file_law_outbox_v1_find_hobom_law_outbox_proto_rawDescData = protoimpl.X.CompressGZIP(file_law_outbox_v1_find_hobom_law_outbox_proto_rawDescData)
	})
	return file_law_outbox_v1_find_hobom_law_outbox_proto_rawDescData
}

var file_law_outbox_v1_find_hobom_law_outbox_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_law_outbox_v1_find_hobom_law_outbox_proto_goTypes = []interface{}{
	(*Request)(nil),           // 0: outbox.law.Request
	(*Response)(nil),          // 1: outbox.law.Response
	(*QueryResult)(nil),       // 2: outbox.law.QueryResult
	(*LawChangedPayload)(nil), // 3: outbox.law.LawChangedPayload
	(*LawArticleChange)(nil),  // 4: outbox.law.LawArticleChange
}
var file_law_outbox_v1_find_hobom_law_outbox_proto_depIdxs = []int32{
	2, // 0: outbox.law.Response.items:type_name -> outbox.law.QueryResult
	3, // 1: outbox.law.QueryResult.payload:type_name -> outbox.law.LawChangedPayload
	4, // 2: outbox.law.LawChangedPayload.changes:type_name -> outbox.law.LawArticleChange
	0, // 3: outbox.law.FindHoBomLawOutboxController.FindOutboxByEventTypeAndStatusUseCase:input_type -> outbox.law.Request
	1, // 4: outbox.law.FindHoBomLawOutboxController.FindOutboxByEventTypeAndStatusUseCase:output_type -> outbox.law.Response
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_law_outbox_v1_find_hobom_law_outbox_proto_init() }
func file_law_outbox_v1_find_hobom_law_outbox_proto_init() {
	if File_law_outbox_v1_find_hobom_law_outbox_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_law_outbox_v1_find_hobom_law_outbox_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_law_outbox_v1_find_hobom_law_outbox_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_law_outbox_v1_find_hobom_law_outbox_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_law_outbox_v1_find_hobom_law_outbox_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LawChangedPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_law_outbox_v1_find_hobom_law_outbox_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LawArticleChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_law_outbox_v1_find_hobom_law_outbox_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_law_outbox_v1_find_hobom_law_outbox_proto_goTypes,
		DependencyIndexes: file_law_outbox_v1_find_hobom_law_outbox_proto_depIdxs,
		MessageInfos:      file_law_outbox_v1_find_hobom_law_outbox_proto_msgTypes,
	}.Build()
	File_law_outbox_v1_find_hobom_law_outbox_proto = out.File
	file_law_outbox_v1_find_hobom_law_outbox_proto_rawDesc = nil
	file_law_outbox_v1_find_hobom_law_outbox_proto_goTypes = nil
	file_law_outbox_v1_find_hobom_law_outbox_proto_depIdxs = nil
}
