// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: law/outbox/v1/find-hobom-law-outbox.proto

package hobomlawpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FindHoBomLawOutboxController_FindOutboxByEventTypeAndStatusUseCase_FullMethodName = "/outbox.law.FindHoBomLawOutboxController/FindOutboxByEventTypeAndStatusUseCase"
)

// FindHoBomLawOutboxControllerClient is the client API for FindHoBomLawOutboxController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FindHoBomLawOutboxControllerClient interface {
	FindOutboxByEventTypeAndStatusUseCase(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type findHoBomLawOutboxControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewFindHoBomLawOutboxControllerClient(cc grpc.ClientConnInterface) FindHoBomLawOutboxControllerClient {
	return &findHoBomLawOutboxControllerClient{cc}
}

func (c *findHoBomLawOutboxControllerClient) FindOutboxByEventTypeAndStatusUseCase(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, FindHoBomLawOutboxController_FindOutboxByEventTypeAndStatusUseCase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FindHoBomLawOutboxControllerServer is the server API for FindHoBomLawOutboxController service.
// All implementations must embed UnimplementedFindHoBomLawOutboxControllerServer
// for forward compatibility.
type FindHoBomLawOutboxControllerServer interface {
	FindOutboxByEventTypeAndStatusUseCase(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedFindHoBomLawOutboxControllerServer()
}

// UnimplementedFindHoBomLawOutboxControllerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFindHoBomLawOutboxControllerServer struct{}

func (UnimplementedFindHoBomLawOutboxControllerServer) FindOutboxByEventTypeAndStatusUseCase(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindOutboxByEventTypeAndStatusUseCase not implemented")
}
func (UnimplementedFindHoBomLawOutboxControllerServer) mustEmbedUnimplementedFindHoBomLawOutboxControllerServer() {
}
func (UnimplementedFindHoBomLawOutboxControllerServer) testEmbeddedByValue() {}

// UnsafeFindHoBomLawOutboxControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FindHoBomLawOutboxControllerServer will
// result in compilation errors.
type UnsafeFindHoBomLawOutboxControllerServer interface {
	mustEmbedUnimplementedFindHoBomLawOutboxControllerServer()
}

func RegisterFindHoBomLawOutboxControllerServer(s grpc.ServiceRegistrar, srv FindHoBomLawOutboxControllerServer) {
	// If the following call pancis, it indicates UnimplementedFindHoBomLawOutboxControllerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FindHoBomLawOutboxController_ServiceDesc, srv)
}

func _FindHoBomLawOutboxController_FindOutboxByEventTypeAndStatusUseCase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FindHoBomLawOutboxControllerServer).FindOutboxByEventTypeAndStatusUseCase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FindHoBomLawOutboxController_FindOutboxByEventTypeAndStatusUseCase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FindHoBomLawOutboxControllerServer).FindOutboxByEventTypeAndStatusUseCase(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// FindHoBomLawOutboxController_ServiceDesc is the grpc.ServiceDesc for FindHoBomLawOutboxController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FindHoBomLawOutboxController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "outbox.law.FindHoBomLawOutboxController",
	HandlerType: (*FindHoBomLawOutboxControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindOutboxByEventTypeAndStatusUseCase",
			Handler:    _FindHoBomLawOutboxController_FindOutboxByEventTypeAndStatusUseCase_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "law/outbox/v1/find-hobom-law-outbox.proto",
}
