// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: angel/outbox/v1/find-hobom-angel-outbox.proto

package hobomangelpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApprovalType int32

const (
	ApprovalType_APPROVAL_TYPE_UNSPECIFIED          ApprovalType = 0
	ApprovalType_APPROVAL_TYPE_SHELTER_VERIFICATION ApprovalType = 1
	ApprovalType_APPROVAL_TYPE_STAFF_PROMOTION      ApprovalType = 2
	ApprovalType_APPROVAL_TYPE_ADOPTION             ApprovalType = 3
	ApprovalType_APPROVAL_TYPE_FOSTER               ApprovalType = 4
)

// Enum value maps for ApprovalType.
var (
	ApprovalType_name = map[int32]string{
		0: "APPROVAL_TYPE_UNSPECIFIED",
		1: "APPROVAL_TYPE_SHELTER_VERIFICATION",
		2: "APPROVAL_TYPE_STAFF_PROMOTION",
		3: "APPROVAL_TYPE_ADOPTION",
		4: "APPROVAL_TYPE_FOSTER",
	}
	ApprovalType_value = map[string]int32{
		"APPROVAL_TYPE_UNSPECIFIED":          0,
		"APPROVAL_TYPE_SHELTER_VERIFICATION": 1,
		"APPROVAL_TYPE_STAFF_PROMOTION":      2,
		"APPROVAL_TYPE_ADOPTION":             3,
		"APPROVAL_TYPE_FOSTER":               4,
	}
)

func (x ApprovalType) Enum() *ApprovalType {
	p := new(ApprovalType)
	*p = x
	return p
}

func (x ApprovalType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApprovalType) Descriptor() protoreflect.EnumDescriptor {
	return file_angel_outbox_v1_find_hobom_angel_outbox_proto_enumTypes[0].Descriptor()
}

func (ApprovalType) Type() protoreflect.EnumType {
	return &file_angel_outbox_v1_find_hobom_angel_outbox_proto_enumTypes[0]
}

func (x ApprovalType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApprovalType.Descriptor instead.
func (ApprovalType) EnumDescriptor() ([]byte, []int) {
	return file_angel_outbox_v1_find_hobom_angel_outbox_proto_rawDescGZIP(), []int{0}
}

type FosterEndReason int32

const (
	FosterEndReason_FOSTER_END_REASON_UNSPECIFIED      FosterEndReason = 0
	FosterEndReason_FOSTER_END_REASON_EXPIRED          FosterEndReason = 1
	FosterEndReason_FOSTER_END_REASON_EARLY_TERMINATED FosterEndReason = 2
)

// Enum value maps for FosterEndReason.
var (
	FosterEndReason_name = map[int32]string{
		0: "FOSTER_END_REASON_UNSPECIFIED",
		1: "FOSTER_END_REASON_EXPIRED",
		2: "FOSTER_END_REASON_EARLY_TERMINATED",
	}
	FosterEndReason_value = map[string]int32{
		"FOSTER_END_REASON_UNSPECIFIED":      0,
		"FOSTER_END_REASON_EXPIRED":          1,
		"FOSTER_END_REASON_EARLY_TERMINATED": 2,
	}
)

func (x FosterEndReason) Enum() *FosterEndReason {
	p := new(FosterEndReason)
	*p = x
	return p
}

func (x FosterEndReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FosterEndReason) Descriptor() protoreflect.EnumDescriptor {
	return file_angel_outbox_v1_find_hobom_angel_outbox_proto_enumTypes[1].Descriptor()
}

func (FosterEndReason) Type() protoreflect.EnumType {
	return &file_angel_outbox_v1_find_hobom_angel_outbox_proto_enumTypes[1]
}

func (x FosterEndReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FosterEndReason.Descriptor instead.
func (FosterEndReason) EnumDescriptor() ([]byte, []int) {
	return file_angel_outbox_v1_find_hobom_angel_outbox_proto_rawDescGZIP(), []int{1}
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=eventType,proto3" json:"eventType,omitempty"` // e.g. ADOPTION_APPROVED, FOSTER_TERMINATED, HOBOM_LOG
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`       // PENDING | SENT | FAILED
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_angel_outbox_v1_find_hobom_angel_outbox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_angel_outbox_v1_find_hobom_angel_outbox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_angel_outbox_v1_find_hobom_angel_outbox_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *Request) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*QueryResult         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_angel_outbox_v1_find_hobom_angel_outbox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_angel_outbox_v1_find_hobom_angel_outbox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_angel_outbox_v1_find_hobom_angel_outbox_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetItems() []*QueryResult {
	if x != nil {
		return x.Items
	}
	return nil
}

// One outbox row. Transport metadata (status/retry/timestamps) wraps a typed,
// discriminated event payload — a real schema, not opaque JSON, so `buf breaking`
// guards its evolution and consumers get a compile-time contract.
type QueryResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=eventId,proto3" json:"eventId,omitempty"`
	EventType     string                 `protobuf:"bytes,3,opt,name=eventType,proto3" json:"eventType,omitempty"`
	Payload       *AngelEventPayload     `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	RetryCount    int32                  `protobuf:"varint,6,opt,name=retryCount,proto3" json:"retryCount,omitempty"`
	SentAt        string                 `protobuf:"bytes,7,opt,name=sentAt,proto3" json:"sentAt,omitempty"`     // ISO-8601, "" when null
	FailedAt      string                 `protobuf:"bytes,8,opt,name=failedAt,proto3" json:"failedAt,omitempty"` // ISO-8601, "" when null
	LastError     string                 `protobuf:"bytes,9,opt,name=lastError,proto3" json:"lastError,omitempty"`
	Version       int32                  `protobuf:"varint,10,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,11,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,12,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResult) Reset() {
	*x = QueryResult{}
	mi := &file_angel_outbox_v1_find_hobom_angel_outbox_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResult) ProtoMessage() {}

func (x *QueryResult) ProtoReflect() protoreflect.Message {
	mi := &file_angel_outbox_v1_find_hobom_angel_outbox_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResult.ProtoReflect.Descriptor instead.
func (*QueryResult) Descriptor() ([]byte, []int) {
	return file_angel_outbox_v1_find_hobom_angel_outbox_proto_rawDescGZIP(), []int{2}
}

func (x *QueryResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QueryResult) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *QueryResult) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *QueryResult) GetPayload() *AngelEventPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *QueryResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *QueryResult) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *QueryResult) GetSentAt() string {
	if x != nil {
		return x.SentAt
	}
	return ""
}

func (x *QueryResult) GetFailedAt() string {
	if x != nil {
		return x.FailedAt
	}
	return ""
}

func (x *QueryResult) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *QueryResult) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *QueryResult) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *QueryResult) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// Discriminated union of Angel event payloads. Exactly one field is set, matching
// the row's `eventType`.
type AngelEventPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*AngelEventPayload_ApprovalApproved
	//	*AngelEventPayload_FosterTerminated
	//	*AngelEventPayload_AccessLog
	Kind          isAngelEventPayload_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AngelEventPayload) Reset() {
	*x = AngelEventPayload{}
	mi := &file_angel_outbox_v1_find_hobom_angel_outbox_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AngelEventPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AngelEventPayload) ProtoMessage() {}

func (x *AngelEventPayload) ProtoReflect() protoreflect.Message {
	mi := &file_angel_outbox_v1_find_hobom_angel_outbox_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AngelEventPayload.ProtoReflect.Descriptor instead.
func (*AngelEventPayload) Descriptor() ([]byte, []int) {
	return file_angel_outbox_v1_find_hobom_angel_outbox_proto_rawDescGZIP(), []int{3}
}

func (x *AngelEventPayload) GetKind() isAngelEventPayload_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *AngelEventPayload) GetApprovalApproved() *ApprovalApproved {
	if x != nil {
		if x, ok := x.Kind.(*AngelEventPayload_ApprovalApproved); ok {
			return x.ApprovalApproved
		}
	}
	return nil
}

func (x *AngelEventPayload) GetFosterTerminated() *FosterTerminated {
	if x != nil {
		if x, ok := x.Kind.(*AngelEventPayload_FosterTerminated); ok {
			return x.FosterTerminated
		}
	}
	return nil
}

func (x *AngelEventPayload) GetAccessLog() *AccessLog {
	if x != nil {
		if x, ok := x.Kind.(*AngelEventPayload_AccessLog); ok {
			return x.AccessLog
		}
	}
	return nil
}

type isAngelEventPayload_Kind interface {
	isAngelEventPayload_Kind()
}

type AngelEventPayload_ApprovalApproved struct {
	ApprovalApproved *ApprovalApproved `protobuf:"bytes,1,opt,name=approval_approved,json=approvalApproved,proto3,oneof"`
}

type AngelEventPayload_FosterTerminated struct {
	FosterTerminated *FosterTerminated `protobuf:"bytes,2,opt,name=foster_terminated,json=fosterTerminated,proto3,oneof"`
}

type AngelEventPayload_AccessLog struct {
	AccessLog *AccessLog `protobuf:"bytes,3,opt,name=access_log,json=accessLog,proto3,oneof"`
}

func (*AngelEventPayload_ApprovalApproved) isAngelEventPayload_Kind() {}

func (*AngelEventPayload_FosterTerminated) isAngelEventPayload_Kind() {}

func (*AngelEventPayload_AccessLog) isAngelEventPayload_Kind() {}

// Any *_APPROVED event: shelter verification, staff promotion, adoption, foster.
// `approval_type` distinguishes which; the shape is shared.
type ApprovalApproved struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ApprovalType    ApprovalType           `protobuf:"varint,1,opt,name=approval_type,json=approvalType,proto3,enum=outbox.angel.ApprovalType" json:"approval_type,omitempty"`
	SubjectRef      string                 `protobuf:"bytes,2,opt,name=subject_ref,json=subjectRef,proto3" json:"subject_ref,omitempty"`                  // decided entity id (shelter / application / candidate)
	RecipientUserId string                 `protobuf:"bytes,3,opt,name=recipient_user_id,json=recipientUserId,proto3" json:"recipient_user_id,omitempty"` // whom to notify
	ShelterId       string                 `protobuf:"bytes,4,opt,name=shelter_id,json=shelterId,proto3" json:"shelter_id,omitempty"`
	OccurredAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ApprovalApproved) Reset() {
	*x = ApprovalApproved{}
	mi := &file_angel_outbox_v1_find_hobom_angel_outbox_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalApproved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalApproved) ProtoMessage() {}

func (x *ApprovalApproved) ProtoReflect() protoreflect.Message {
	mi := &file_angel_outbox_v1_find_hobom_angel_outbox_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalApproved.ProtoReflect.Descriptor instead.
func (*ApprovalApproved) Descriptor() ([]byte, []int) {
	return file_angel_outbox_v1_find_hobom_angel_outbox_proto_rawDescGZIP(), []int{4}
}

func (x *ApprovalApproved) GetApprovalType() ApprovalType {
	if x != nil {
		return x.ApprovalType
	}
	return ApprovalType_APPROVAL_TYPE_UNSPECIFIED
}

func (x *ApprovalApproved) GetSubjectRef() string {
	if x != nil {
		return x.SubjectRef
	}
	return ""
}

func (x *ApprovalApproved) GetRecipientUserId() string {
	if x != nil {
		return x.RecipientUserId
	}
	return ""
}

func (x *ApprovalApproved) GetShelterId() string {
	if x != nil {
		return x.ShelterId
	}
	return ""
}

func (x *ApprovalApproved) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

// FOSTER_TERMINATED: an active foster ended (expiry or early termination).
type FosterTerminated struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FosterProcessId string                 `protobuf:"bytes,1,opt,name=foster_process_id,json=fosterProcessId,proto3" json:"foster_process_id,omitempty"`
	AnimalId        string                 `protobuf:"bytes,2,opt,name=animal_id,json=animalId,proto3" json:"animal_id,omitempty"`
	RecipientUserId string                 `protobuf:"bytes,3,opt,name=recipient_user_id,json=recipientUserId,proto3" json:"recipient_user_id,omitempty"`
	Reason          FosterEndReason        `protobuf:"varint,4,opt,name=reason,proto3,enum=outbox.angel.FosterEndReason" json:"reason,omitempty"`
	OccurredAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FosterTerminated) Reset() {
	*x = FosterTerminated{}
	mi := &file_angel_outbox_v1_find_hobom_angel_outbox_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FosterTerminated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FosterTerminated) ProtoMessage() {}

func (x *FosterTerminated) ProtoReflect() protoreflect.Message {
	mi := &file_angel_outbox_v1_find_hobom_angel_outbox_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FosterTerminated.ProtoReflect.Descriptor instead.
func (*FosterTerminated) Descriptor() ([]byte, []int) {
	return file_angel_outbox_v1_find_hobom_angel_outbox_proto_rawDescGZIP(), []int{5}
}

func (x *FosterTerminated) GetFosterProcessId() string {
	if x != nil {
		return x.FosterProcessId
	}
	return ""
}

func (x *FosterTerminated) GetAnimalId() string {
	if x != nil {
		return x.AnimalId
	}
	return ""
}

func (x *FosterTerminated) GetRecipientUserId() string {
	if x != nil {
		return x.RecipientUserId
	}
	return ""
}

func (x *FosterTerminated) GetReason() FosterEndReason {
	if x != nil {
		return x.Reason
	}
	return FosterEndReason_FOSTER_END_REASON_UNSPECIFIED
}

func (x *FosterTerminated) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

// HOBOM_LOG: best-effort redacted HTTP access log shipped via the outbox.
type AccessLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"` // INFO | ERROR
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	StatusCode    int32                  `protobuf:"varint,5,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Host          string                 `protobuf:"bytes,6,opt,name=host,proto3" json:"host,omitempty"`
	UserId        string                 `protobuf:"bytes,7,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Message       string                 `protobuf:"bytes,8,opt,name=message,proto3" json:"message,omitempty"`
	Meta          map[string]string      `protobuf:"bytes,9,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // redacted request context (never raw PII/secrets)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessLog) Reset() {
	*x = AccessLog{}
	mi := &file_angel_outbox_v1_find_hobom_angel_outbox_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessLog) ProtoMessage() {}

func (x *AccessLog) ProtoReflect() protoreflect.Message {
	mi := &file_angel_outbox_v1_find_hobom_angel_outbox_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessLog.ProtoReflect.Descriptor instead.
func (*AccessLog) Descriptor() ([]byte, []int) {
	return file_angel_outbox_v1_find_hobom_angel_outbox_proto_rawDescGZIP(), []int{6}
}

func (x *AccessLog) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *AccessLog) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *AccessLog) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *AccessLog) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *AccessLog) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *AccessLog) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *AccessLog) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AccessLog) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AccessLog) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

var File_angel_outbox_v1_find_hobom_angel_outbox_proto protoreflect.FileDescriptor

const file_angel_outbox_v1_find_hobom_angel_outbox_proto_rawDesc = "" +
	"\n" +
	"-angel/outbox/v1/find-hobom-angel-outbox.proto\x12\foutbox.angel\x1a\x1fgoogle/protobuf/timestamp.proto\"?\n" +
	"\aRequest\x12\x1c\n" +
	"\teventType\x18\x01 \x01(\tR\teventType\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\";\n" +
	"\bResponse\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.outbox.angel.QueryResultR\x05items\"\xf0\x02\n" +
	"\vQueryResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aeventId\x18\x02 \x01(\tR\aeventId\x12\x1c\n" +
	"\teventType\x18\x03 \x01(\tR\teventType\x129\n" +
	"\apayload\x18\x04 \x01(\v2\x1f.outbox.angel.AngelEventPayloadR\apayload\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"retryCount\x18\x06 \x01(\x05R\n" +
	"retryCount\x12\x16\n" +
	"\x06sentAt\x18\a \x01(\tR\x06sentAt\x12\x1a\n" +
	"\bfailedAt\x18\b \x01(\tR\bfailedAt\x12\x1c\n" +
	"\tlastError\x18\t \x01(\tR\tlastError\x12\x18\n" +
	"\aversion\x18\n" +
	" \x01(\x05R\aversion\x12\x1c\n" +
	"\tcreatedAt\x18\v \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\f \x01(\tR\tupdatedAt\"\xf3\x01\n" +
	"\x11AngelEventPayload\x12M\n" +
	"\x11approval_approved\x18\x01 \x01(\v2\x1e.outbox.angel.ApprovalApprovedH\x00R\x10approvalApproved\x12M\n" +
	"\x11foster_terminated\x18\x02 \x01(\v2\x1e.outbox.angel.FosterTerminatedH\x00R\x10fosterTerminated\x128\n" +
	"\n" +
	"access_log\x18\x03 \x01(\v2\x17.outbox.angel.AccessLogH\x00R\taccessLogB\x06\n" +
	"\x04kind\"\xfc\x01\n" +
	"\x10ApprovalApproved\x12?\n" +
	"\rapproval_type\x18\x01 \x01(\x0e2\x1a.outbox.angel.ApprovalTypeR\fapprovalType\x12\x1f\n" +
	"\vsubject_ref\x18\x02 \x01(\tR\n" +
	"subjectRef\x12*\n" +
	"\x11recipient_user_id\x18\x03 \x01(\tR\x0frecipientUserId\x12\x1d\n" +
	"\n" +
	"shelter_id\x18\x04 \x01(\tR\tshelterId\x12;\n" +
	"\voccurred_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\"\xfb\x01\n" +
	"\x10FosterTerminated\x12*\n" +
	"\x11foster_process_id\x18\x01 \x01(\tR\x0ffosterProcessId\x12\x1b\n" +
	"\tanimal_id\x18\x02 \x01(\tR\banimalId\x12*\n" +
	"\x11recipient_user_id\x18\x03 \x01(\tR\x0frecipientUserId\x125\n" +
	"\x06reason\x18\x04 \x01(\x0e2\x1d.outbox.angel.FosterEndReasonR\x06reason\x12;\n" +
	"\voccurred_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\"\xc0\x02\n" +
	"\tAccessLog\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x1f\n" +
	"\vstatus_code\x18\x05 \x01(\x05R\n" +
	"statusCode\x12\x12\n" +
	"\x04host\x18\x06 \x01(\tR\x04host\x12\x17\n" +
	"\auser_id\x18\a \x01(\tR\x06userId\x12\x18\n" +
	"\amessage\x18\b \x01(\tR\amessage\x125\n" +
	"\x04meta\x18\t \x03(\v2!.outbox.angel.AccessLog.MetaEntryR\x04meta\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xae\x01\n" +
	"\fApprovalType\x12\x1d\n" +
	"\x19APPROVAL_TYPE_UNSPECIFIED\x10\x00\x12&\n" +
	"\"APPROVAL_TYPE_SHELTER_VERIFICATION\x10\x01\x12!\n" +
	"\x1dAPPROVAL_TYPE_STAFF_PROMOTION\x10\x02\x12\x1a\n" +
	"\x16APPROVAL_TYPE_ADOPTION\x10\x03\x12\x18\n" +
	"\x14APPROVAL_TYPE_FOSTER\x10\x04*{\n" +
	"\x0fFosterEndReason\x12!\n" +
	"\x1dFOSTER_END_REASON_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19FOSTER_END_REASON_EXPIRED\x10\x01\x12&\n" +
	"\"FOSTER_END_REASON_EARLY_TERMINATED\x10\x022x\n" +
	"\x1eFindHoBomAngelOutboxController\x12V\n" +
	"%FindOutboxByEventTypeAndStatusUseCase\x12\x15.outbox.angel.Request\x1a\x16.outbox.angel.ResponseBXZVgithub.com/HoBom-s/hobom-event-processor/infra/grpc/v1/hobom-angel-outbox;hobomangelpbb\x06proto3"

var (
	file_angel_outbox_v1_find_hobom_angel_outbox_proto_rawDescOnce sync.Once
	file_angel_outbox_v1_find_hobom_angel_outbox_proto_rawDescData []byte
)

func file_angel_outbox_v1_find_hobom_angel_outbox_proto_rawDescGZIP() []byte {
	file_angel_outbox_v1_find_hobom_angel_outbox_proto_rawDescOnce.Do(func() {
		file_angel_outbox_v1_find_hobom_angel_outbox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_angel_outbox_v1_find_hobom_angel_outbox_proto_rawDesc), len(file_angel_outbox_v1_find_hobom_angel_outbox_proto_rawDesc)))
	})
	return file_angel_outbox_v1_find_hobom_angel_outbox_proto_rawDescData
}

var file_angel_outbox_v1_find_hobom_angel_outbox_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_angel_outbox_v1_find_hobom_angel_outbox_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_angel_outbox_v1_find_hobom_angel_outbox_proto_goTypes = []any{
	(ApprovalType)(0),             // 0: outbox.angel.ApprovalType
	(FosterEndReason)(0),          // 1: outbox.angel.FosterEndReason
	(*Request)(nil),               // 2: outbox.angel.Request
	(*Response)(nil),              // 3: outbox.angel.Response
	(*QueryResult)(nil),           // 4: outbox.angel.QueryResult
	(*AngelEventPayload)(nil),     // 5: outbox.angel.AngelEventPayload
	(*ApprovalApproved)(nil),      // 6: outbox.angel.ApprovalApproved
	(*FosterTerminated)(nil),      // 7: outbox.angel.FosterTerminated
	(*AccessLog)(nil),             // 8: outbox.angel.AccessLog
	nil,                           // 9: outbox.angel.AccessLog.MetaEntry
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_angel_outbox_v1_find_hobom_angel_outbox_proto_depIdxs = []int32{
	4,  // 0: outbox.angel.Response.items:type_name -> outbox.angel.QueryResult
	5,  // 1: outbox.angel.QueryResult.payload:type_name -> outbox.angel.AngelEventPayload
	6,  // 2: outbox.angel.AngelEventPayload.approval_approved:type_name -> outbox.angel.ApprovalApproved
	7,  // 3: outbox.angel.AngelEventPayload.foster_terminated:type_name -> outbox.angel.FosterTerminated
	8,  // 4: outbox.angel.AngelEventPayload.access_log:type_name -> outbox.angel.AccessLog
	0,  // 5: outbox.angel.ApprovalApproved.approval_type:type_name -> outbox.angel.ApprovalType
	10, // 6: outbox.angel.ApprovalApproved.occurred_at:type_name -> google.protobuf.Timestamp
	1,  // 7: outbox.angel.FosterTerminated.reason:type_name -> outbox.angel.FosterEndReason
	10, // 8: outbox.angel.FosterTerminated.occurred_at:type_name -> google.protobuf.Timestamp
	9,  // 9: outbox.angel.AccessLog.meta:type_name -> outbox.angel.AccessLog.MetaEntry
	2,  // 10: outbox.angel.FindHoBomAngelOutboxController.FindOutboxByEventTypeAndStatusUseCase:input_type -> outbox.angel.Request
	3,  // 11: outbox.angel.FindHoBomAngelOutboxController.FindOutboxByEventTypeAndStatusUseCase:output_type -> outbox.angel.Response
	11, // [11:12] is the sub-list for method output_type
	10, // [10:11] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_angel_outbox_v1_find_hobom_angel_outbox_proto_init() }
func file_angel_outbox_v1_find_hobom_angel_outbox_proto_init() {
	if File_angel_outbox_v1_find_hobom_angel_outbox_proto != nil {
		return
	}
	file_angel_outbox_v1_find_hobom_angel_outbox_proto_msgTypes[3].OneofWrappers = []any{
		(*AngelEventPayload_ApprovalApproved)(nil),
		(*AngelEventPayload_FosterTerminated)(nil),
		(*AngelEventPayload_AccessLog)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_angel_outbox_v1_find_hobom_angel_outbox_proto_rawDesc), len(file_angel_outbox_v1_find_hobom_angel_outbox_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_angel_outbox_v1_find_hobom_angel_outbox_proto_goTypes,
		DependencyIndexes: file_angel_outbox_v1_find_hobom_angel_outbox_proto_depIdxs,
		EnumInfos:         file_angel_outbox_v1_find_hobom_angel_outbox_proto_enumTypes,
		MessageInfos:      file_angel_outbox_v1_find_hobom_angel_outbox_proto_msgTypes,
	}.Build()
	File_angel_outbox_v1_find_hobom_angel_outbox_proto = out.File
	file_angel_outbox_v1_find_hobom_angel_outbox_proto_goTypes = nil
	file_angel_outbox_v1_find_hobom_angel_outbox_proto_depIdxs = nil
}
