// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: angel/outbox/v1/find-hobom-angel-outbox.proto

package hobomangelpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FindHoBomAngelOutboxController_FindOutboxByEventTypeAndStatusUseCase_FullMethodName = "/outbox.angel.FindHoBomAngelOutboxController/FindOutboxByEventTypeAndStatusUseCase"
)

// FindHoBomAngelOutboxControllerClient is the client API for FindHoBomAngelOutboxController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Polled by hobom-event-processor (AngelPoller): fetch outbox rows for an event
// type + status, publish each PENDING row to the Kafka topic `hobom.angel-events`,
// then advance it via PatchHoBomAngelOutboxController.
type FindHoBomAngelOutboxControllerClient interface {
	FindOutboxByEventTypeAndStatusUseCase(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type findHoBomAngelOutboxControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewFindHoBomAngelOutboxControllerClient(cc grpc.ClientConnInterface) FindHoBomAngelOutboxControllerClient {
	return &findHoBomAngelOutboxControllerClient{cc}
}

func (c *findHoBomAngelOutboxControllerClient) FindOutboxByEventTypeAndStatusUseCase(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, FindHoBomAngelOutboxController_FindOutboxByEventTypeAndStatusUseCase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FindHoBomAngelOutboxControllerServer is the server API for FindHoBomAngelOutboxController service.
// All implementations must embed UnimplementedFindHoBomAngelOutboxControllerServer
// for forward compatibility.
//
// Polled by hobom-event-processor (AngelPoller): fetch outbox rows for an event
// type + status, publish each PENDING row to the Kafka topic `hobom.angel-events`,
// then advance it via PatchHoBomAngelOutboxController.
type FindHoBomAngelOutboxControllerServer interface {
	FindOutboxByEventTypeAndStatusUseCase(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedFindHoBomAngelOutboxControllerServer()
}

// UnimplementedFindHoBomAngelOutboxControllerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFindHoBomAngelOutboxControllerServer struct{}

func (UnimplementedFindHoBomAngelOutboxControllerServer) FindOutboxByEventTypeAndStatusUseCase(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindOutboxByEventTypeAndStatusUseCase not implemented")
}
func (UnimplementedFindHoBomAngelOutboxControllerServer) mustEmbedUnimplementedFindHoBomAngelOutboxControllerServer() {
}
func (UnimplementedFindHoBomAngelOutboxControllerServer) testEmbeddedByValue() {}

// UnsafeFindHoBomAngelOutboxControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FindHoBomAngelOutboxControllerServer will
// result in compilation errors.
type UnsafeFindHoBomAngelOutboxControllerServer interface {
	mustEmbedUnimplementedFindHoBomAngelOutboxControllerServer()
}

func RegisterFindHoBomAngelOutboxControllerServer(s grpc.ServiceRegistrar, srv FindHoBomAngelOutboxControllerServer) {
	// If the following call pancis, it indicates UnimplementedFindHoBomAngelOutboxControllerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FindHoBomAngelOutboxController_ServiceDesc, srv)
}

func _FindHoBomAngelOutboxController_FindOutboxByEventTypeAndStatusUseCase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FindHoBomAngelOutboxControllerServer).FindOutboxByEventTypeAndStatusUseCase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FindHoBomAngelOutboxController_FindOutboxByEventTypeAndStatusUseCase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FindHoBomAngelOutboxControllerServer).FindOutboxByEventTypeAndStatusUseCase(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// FindHoBomAngelOutboxController_ServiceDesc is the grpc.ServiceDesc for FindHoBomAngelOutboxController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FindHoBomAngelOutboxController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "outbox.angel.FindHoBomAngelOutboxController",
	HandlerType: (*FindHoBomAngelOutboxControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindOutboxByEventTypeAndStatusUseCase",
			Handler:    _FindHoBomAngelOutboxController_FindOutboxByEventTypeAndStatusUseCase_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "angel/outbox/v1/find-hobom-angel-outbox.proto",
}
