// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: angel/outbox/v1/patch-hobom-angel-outbox.proto

package hobomangelpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PatchHoBomAngelOutboxController_PatchOutboxMarkAsSentUseCase_FullMethodName   = "/outbox.angel.PatchHoBomAngelOutboxController/PatchOutboxMarkAsSentUseCase"
	PatchHoBomAngelOutboxController_PatchOutboxMarkAsFailedUseCase_FullMethodName = "/outbox.angel.PatchHoBomAngelOutboxController/PatchOutboxMarkAsFailedUseCase"
)

// PatchHoBomAngelOutboxControllerClient is the client API for PatchHoBomAngelOutboxController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Called by the processor after each publish attempt to advance the outbox row:
// SENT on success, FAILED (with the error) on failure. The Angel backend applies
// these with optimistic concurrency and bumps retryCount on failure.
type PatchHoBomAngelOutboxControllerClient interface {
	PatchOutboxMarkAsSentUseCase(ctx context.Context, in *MarkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	PatchOutboxMarkAsFailedUseCase(ctx context.Context, in *MarkFailedRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type patchHoBomAngelOutboxControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewPatchHoBomAngelOutboxControllerClient(cc grpc.ClientConnInterface) PatchHoBomAngelOutboxControllerClient {
	return &patchHoBomAngelOutboxControllerClient{cc}
}

func (c *patchHoBomAngelOutboxControllerClient) PatchOutboxMarkAsSentUseCase(ctx context.Context, in *MarkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PatchHoBomAngelOutboxController_PatchOutboxMarkAsSentUseCase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *patchHoBomAngelOutboxControllerClient) PatchOutboxMarkAsFailedUseCase(ctx context.Context, in *MarkFailedRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PatchHoBomAngelOutboxController_PatchOutboxMarkAsFailedUseCase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PatchHoBomAngelOutboxControllerServer is the server API for PatchHoBomAngelOutboxController service.
// All implementations must embed UnimplementedPatchHoBomAngelOutboxControllerServer
// for forward compatibility.
//
// Called by the processor after each publish attempt to advance the outbox row:
// SENT on success, FAILED (with the error) on failure. The Angel backend applies
// these with optimistic concurrency and bumps retryCount on failure.
type PatchHoBomAngelOutboxControllerServer interface {
	PatchOutboxMarkAsSentUseCase(context.Context, *MarkRequest) (*emptypb.Empty, error)
	PatchOutboxMarkAsFailedUseCase(context.Context, *MarkFailedRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedPatchHoBomAngelOutboxControllerServer()
}

// UnimplementedPatchHoBomAngelOutboxControllerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPatchHoBomAngelOutboxControllerServer struct{}

func (UnimplementedPatchHoBomAngelOutboxControllerServer) PatchOutboxMarkAsSentUseCase(context.Context, *MarkRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PatchOutboxMarkAsSentUseCase not implemented")
}
func (UnimplementedPatchHoBomAngelOutboxControllerServer) PatchOutboxMarkAsFailedUseCase(context.Context, *MarkFailedRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PatchOutboxMarkAsFailedUseCase not implemented")
}
func (UnimplementedPatchHoBomAngelOutboxControllerServer) mustEmbedUnimplementedPatchHoBomAngelOutboxControllerServer() {
}
func (UnimplementedPatchHoBomAngelOutboxControllerServer) testEmbeddedByValue() {}

// UnsafePatchHoBomAngelOutboxControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PatchHoBomAngelOutboxControllerServer will
// result in compilation errors.
type UnsafePatchHoBomAngelOutboxControllerServer interface {
	mustEmbedUnimplementedPatchHoBomAngelOutboxControllerServer()
}

func RegisterPatchHoBomAngelOutboxControllerServer(s grpc.ServiceRegistrar, srv PatchHoBomAngelOutboxControllerServer) {
	// If the following call pancis, it indicates UnimplementedPatchHoBomAngelOutboxControllerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PatchHoBomAngelOutboxController_ServiceDesc, srv)
}

func _PatchHoBomAngelOutboxController_PatchOutboxMarkAsSentUseCase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PatchHoBomAngelOutboxControllerServer).PatchOutboxMarkAsSentUseCase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PatchHoBomAngelOutboxController_PatchOutboxMarkAsSentUseCase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PatchHoBomAngelOutboxControllerServer).PatchOutboxMarkAsSentUseCase(ctx, req.(*MarkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PatchHoBomAngelOutboxController_PatchOutboxMarkAsFailedUseCase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkFailedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PatchHoBomAngelOutboxControllerServer).PatchOutboxMarkAsFailedUseCase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PatchHoBomAngelOutboxController_PatchOutboxMarkAsFailedUseCase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PatchHoBomAngelOutboxControllerServer).PatchOutboxMarkAsFailedUseCase(ctx, req.(*MarkFailedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PatchHoBomAngelOutboxController_ServiceDesc is the grpc.ServiceDesc for PatchHoBomAngelOutboxController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PatchHoBomAngelOutboxController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "outbox.angel.PatchHoBomAngelOutboxController",
	HandlerType: (*PatchHoBomAngelOutboxControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PatchOutboxMarkAsSentUseCase",
			Handler:    _PatchHoBomAngelOutboxController_PatchOutboxMarkAsSentUseCase_Handler,
		},
		{
			MethodName: "PatchOutboxMarkAsFailedUseCase",
			Handler:    _PatchHoBomAngelOutboxController_PatchOutboxMarkAsFailedUseCase_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "angel/outbox/v1/patch-hobom-angel-outbox.proto",
}
