// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: space/outbox/v1/find-hobom-space-outbox.proto

package hobomspacepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FindHoBomSpaceOutboxController_FindOutboxByEventTypeAndStatusUseCase_FullMethodName = "/outbox.space.FindHoBomSpaceOutboxController/FindOutboxByEventTypeAndStatusUseCase"
)

// FindHoBomSpaceOutboxControllerClient is the client API for FindHoBomSpaceOutboxController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FindHoBomSpaceOutboxControllerClient interface {
	FindOutboxByEventTypeAndStatusUseCase(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type findHoBomSpaceOutboxControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewFindHoBomSpaceOutboxControllerClient(cc grpc.ClientConnInterface) FindHoBomSpaceOutboxControllerClient {
	return &findHoBomSpaceOutboxControllerClient{cc}
}

func (c *findHoBomSpaceOutboxControllerClient) FindOutboxByEventTypeAndStatusUseCase(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, FindHoBomSpaceOutboxController_FindOutboxByEventTypeAndStatusUseCase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FindHoBomSpaceOutboxControllerServer is the server API for FindHoBomSpaceOutboxController service.
// All implementations must embed UnimplementedFindHoBomSpaceOutboxControllerServer
// for forward compatibility.
type FindHoBomSpaceOutboxControllerServer interface {
	FindOutboxByEventTypeAndStatusUseCase(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedFindHoBomSpaceOutboxControllerServer()
}

// UnimplementedFindHoBomSpaceOutboxControllerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFindHoBomSpaceOutboxControllerServer struct{}

func (UnimplementedFindHoBomSpaceOutboxControllerServer) FindOutboxByEventTypeAndStatusUseCase(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindOutboxByEventTypeAndStatusUseCase not implemented")
}
func (UnimplementedFindHoBomSpaceOutboxControllerServer) mustEmbedUnimplementedFindHoBomSpaceOutboxControllerServer() {
}
func (UnimplementedFindHoBomSpaceOutboxControllerServer) testEmbeddedByValue() {}

// UnsafeFindHoBomSpaceOutboxControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FindHoBomSpaceOutboxControllerServer will
// result in compilation errors.
type UnsafeFindHoBomSpaceOutboxControllerServer interface {
	mustEmbedUnimplementedFindHoBomSpaceOutboxControllerServer()
}

func RegisterFindHoBomSpaceOutboxControllerServer(s grpc.ServiceRegistrar, srv FindHoBomSpaceOutboxControllerServer) {
	// If the following call pancis, it indicates UnimplementedFindHoBomSpaceOutboxControllerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FindHoBomSpaceOutboxController_ServiceDesc, srv)
}

func _FindHoBomSpaceOutboxController_FindOutboxByEventTypeAndStatusUseCase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FindHoBomSpaceOutboxControllerServer).FindOutboxByEventTypeAndStatusUseCase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FindHoBomSpaceOutboxController_FindOutboxByEventTypeAndStatusUseCase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FindHoBomSpaceOutboxControllerServer).FindOutboxByEventTypeAndStatusUseCase(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// FindHoBomSpaceOutboxController_ServiceDesc is the grpc.ServiceDesc for FindHoBomSpaceOutboxController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FindHoBomSpaceOutboxController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "outbox.space.FindHoBomSpaceOutboxController",
	HandlerType: (*FindHoBomSpaceOutboxControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindOutboxByEventTypeAndStatusUseCase",
			Handler:    _FindHoBomSpaceOutboxController_FindOutboxByEventTypeAndStatusUseCase_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "space/outbox/v1/find-hobom-space-outbox.proto",
}
