// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: space/outbox/v1/find-hobom-space-outbox.proto

package hobomspacepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=eventType,proto3" json:"eventType,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_space_outbox_v1_find_hobom_space_outbox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_space_outbox_v1_find_hobom_space_outbox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_space_outbox_v1_find_hobom_space_outbox_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *Request) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*QueryResult         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_space_outbox_v1_find_hobom_space_outbox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_space_outbox_v1_find_hobom_space_outbox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_space_outbox_v1_find_hobom_space_outbox_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetItems() []*QueryResult {
	if x != nil {
		return x.Items
	}
	return nil
}

type QueryResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=eventId,proto3" json:"eventId,omitempty"`
	EventType     string                 `protobuf:"bytes,3,opt,name=eventType,proto3" json:"eventType,omitempty"`
	Payload       *SpaceEventPayload     `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	RetryCount    int32                  `protobuf:"varint,6,opt,name=retryCount,proto3" json:"retryCount,omitempty"`
	SentAt        string                 `protobuf:"bytes,7,opt,name=sentAt,proto3" json:"sentAt,omitempty"`
	FailedAt      string                 `protobuf:"bytes,8,opt,name=failedAt,proto3" json:"failedAt,omitempty"`
	LastError     string                 `protobuf:"bytes,9,opt,name=lastError,proto3" json:"lastError,omitempty"`
	Version       int32                  `protobuf:"varint,10,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,11,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,12,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResult) Reset() {
	*x = QueryResult{}
	mi := &file_space_outbox_v1_find_hobom_space_outbox_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResult) ProtoMessage() {}

func (x *QueryResult) ProtoReflect() protoreflect.Message {
	mi := &file_space_outbox_v1_find_hobom_space_outbox_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResult.ProtoReflect.Descriptor instead.
func (*QueryResult) Descriptor() ([]byte, []int) {
	return file_space_outbox_v1_find_hobom_space_outbox_proto_rawDescGZIP(), []int{2}
}

func (x *QueryResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QueryResult) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *QueryResult) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *QueryResult) GetPayload() *SpaceEventPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *QueryResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *QueryResult) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *QueryResult) GetSentAt() string {
	if x != nil {
		return x.SentAt
	}
	return ""
}

func (x *QueryResult) GetFailedAt() string {
	if x != nil {
		return x.FailedAt
	}
	return ""
}

func (x *QueryResult) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *QueryResult) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *QueryResult) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *QueryResult) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type SpaceEventPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityType    string                 `protobuf:"bytes,1,opt,name=entityType,proto3" json:"entityType,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	SpaceKey      string                 `protobuf:"bytes,3,opt,name=spaceKey,proto3" json:"spaceKey,omitempty"`
	PageId        int64                  `protobuf:"varint,4,opt,name=pageId,proto3" json:"pageId,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	ActorId       string                 `protobuf:"bytes,6,opt,name=actorId,proto3" json:"actorId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpaceEventPayload) Reset() {
	*x = SpaceEventPayload{}
	mi := &file_space_outbox_v1_find_hobom_space_outbox_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpaceEventPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpaceEventPayload) ProtoMessage() {}

func (x *SpaceEventPayload) ProtoReflect() protoreflect.Message {
	mi := &file_space_outbox_v1_find_hobom_space_outbox_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpaceEventPayload.ProtoReflect.Descriptor instead.
func (*SpaceEventPayload) Descriptor() ([]byte, []int) {
	return file_space_outbox_v1_find_hobom_space_outbox_proto_rawDescGZIP(), []int{3}
}

func (x *SpaceEventPayload) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *SpaceEventPayload) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *SpaceEventPayload) GetSpaceKey() string {
	if x != nil {
		return x.SpaceKey
	}
	return ""
}

func (x *SpaceEventPayload) GetPageId() int64 {
	if x != nil {
		return x.PageId
	}
	return 0
}

func (x *SpaceEventPayload) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SpaceEventPayload) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

var File_space_outbox_v1_find_hobom_space_outbox_proto protoreflect.FileDescriptor

const file_space_outbox_v1_find_hobom_space_outbox_proto_rawDesc = "" +
	"\n" +
	"-space/outbox/v1/find-hobom-space-outbox.proto\x12\foutbox.space\"?\n" +
	"\aRequest\x12\x1c\n" +
	"\teventType\x18\x01 \x01(\tR\teventType\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\";\n" +
	"\bResponse\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.outbox.space.QueryResultR\x05items\"\xf0\x02\n" +
	"\vQueryResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aeventId\x18\x02 \x01(\tR\aeventId\x12\x1c\n" +
	"\teventType\x18\x03 \x01(\tR\teventType\x129\n" +
	"\apayload\x18\x04 \x01(\v2\x1f.outbox.space.SpaceEventPayloadR\apayload\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"retryCount\x18\x06 \x01(\x05R\n" +
	"retryCount\x12\x16\n" +
	"\x06sentAt\x18\a \x01(\tR\x06sentAt\x12\x1a\n" +
	"\bfailedAt\x18\b \x01(\tR\bfailedAt\x12\x1c\n" +
	"\tlastError\x18\t \x01(\tR\tlastError\x12\x18\n" +
	"\aversion\x18\n" +
	" \x01(\x05R\aversion\x12\x1c\n" +
	"\tcreatedAt\x18\v \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\f \x01(\tR\tupdatedAt\"\xaf\x01\n" +
	"\x11SpaceEventPayload\x12\x1e\n" +
	"\n" +
	"entityType\x18\x01 \x01(\tR\n" +
	"entityType\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x1a\n" +
	"\bspaceKey\x18\x03 \x01(\tR\bspaceKey\x12\x16\n" +
	"\x06pageId\x18\x04 \x01(\x03R\x06pageId\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x18\n" +
	"\aactorId\x18\x06 \x01(\tR\aactorId2x\n" +
	"\x1eFindHoBomSpaceOutboxController\x12V\n" +
	"%FindOutboxByEventTypeAndStatusUseCase\x12\x15.outbox.space.Request\x1a\x16.outbox.space.ResponseBXZVgithub.com/HoBom-s/hobom-event-processor/infra/grpc/v1/hobom-space-outbox;hobomspacepbb\x06proto3"

var (
	file_space_outbox_v1_find_hobom_space_outbox_proto_rawDescOnce sync.Once
	file_space_outbox_v1_find_hobom_space_outbox_proto_rawDescData []byte
)

func file_space_outbox_v1_find_hobom_space_outbox_proto_rawDescGZIP() []byte {
	file_space_outbox_v1_find_hobom_space_outbox_proto_rawDescOnce.Do(func() {
		file_space_outbox_v1_find_hobom_space_outbox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_space_outbox_v1_find_hobom_space_outbox_proto_rawDesc), len(file_space_outbox_v1_find_hobom_space_outbox_proto_rawDesc)))
	})
	return file_space_outbox_v1_find_hobom_space_outbox_proto_rawDescData
}

var file_space_outbox_v1_find_hobom_space_outbox_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_space_outbox_v1_find_hobom_space_outbox_proto_goTypes = []any{
	(*Request)(nil),           // 0: outbox.space.Request
	(*Response)(nil),          // 1: outbox.space.Response
	(*QueryResult)(nil),       // 2: outbox.space.QueryResult
	(*SpaceEventPayload)(nil), // 3: outbox.space.SpaceEventPayload
}
var file_space_outbox_v1_find_hobom_space_outbox_proto_depIdxs = []int32{
	2, // 0: outbox.space.Response.items:type_name -> outbox.space.QueryResult
	3, // 1: outbox.space.QueryResult.payload:type_name -> outbox.space.SpaceEventPayload
	0, // 2: outbox.space.FindHoBomSpaceOutboxController.FindOutboxByEventTypeAndStatusUseCase:input_type -> outbox.space.Request
	1, // 3: outbox.space.FindHoBomSpaceOutboxController.FindOutboxByEventTypeAndStatusUseCase:output_type -> outbox.space.Response
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_space_outbox_v1_find_hobom_space_outbox_proto_init() }
func file_space_outbox_v1_find_hobom_space_outbox_proto_init() {
	if File_space_outbox_v1_find_hobom_space_outbox_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_space_outbox_v1_find_hobom_space_outbox_proto_rawDesc), len(file_space_outbox_v1_find_hobom_space_outbox_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_space_outbox_v1_find_hobom_space_outbox_proto_goTypes,
		DependencyIndexes: file_space_outbox_v1_find_hobom_space_outbox_proto_depIdxs,
		MessageInfos:      file_space_outbox_v1_find_hobom_space_outbox_proto_msgTypes,
	}.Build()
	File_space_outbox_v1_find_hobom_space_outbox_proto = out.File
	file_space_outbox_v1_find_hobom_space_outbox_proto_goTypes = nil
	file_space_outbox_v1_find_hobom_space_outbox_proto_depIdxs = nil
}
