// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: space/outbox/v1/patch-hobom-space-outbox.proto

package hobomspacepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PatchHoBomSpaceOutboxController_PatchOutboxMarkAsSentUseCase_FullMethodName   = "/outbox.space.PatchHoBomSpaceOutboxController/PatchOutboxMarkAsSentUseCase"
	PatchHoBomSpaceOutboxController_PatchOutboxMarkAsFailedUseCase_FullMethodName = "/outbox.space.PatchHoBomSpaceOutboxController/PatchOutboxMarkAsFailedUseCase"
)

// PatchHoBomSpaceOutboxControllerClient is the client API for PatchHoBomSpaceOutboxController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PatchHoBomSpaceOutboxControllerClient interface {
	PatchOutboxMarkAsSentUseCase(ctx context.Context, in *MarkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	PatchOutboxMarkAsFailedUseCase(ctx context.Context, in *MarkFailedRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type patchHoBomSpaceOutboxControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewPatchHoBomSpaceOutboxControllerClient(cc grpc.ClientConnInterface) PatchHoBomSpaceOutboxControllerClient {
	return &patchHoBomSpaceOutboxControllerClient{cc}
}

func (c *patchHoBomSpaceOutboxControllerClient) PatchOutboxMarkAsSentUseCase(ctx context.Context, in *MarkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PatchHoBomSpaceOutboxController_PatchOutboxMarkAsSentUseCase_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *patchHoBomSpaceOutboxControllerClient) PatchOutboxMarkAsFailedUseCase(ctx context.Context, in *MarkFailedRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PatchHoBomSpaceOutboxController_PatchOutboxMarkAsFailedUseCase_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PatchHoBomSpaceOutboxControllerServer is the server API for PatchHoBomSpaceOutboxController service.
// All implementations must embed UnimplementedPatchHoBomSpaceOutboxControllerServer
// for forward compatibility
type PatchHoBomSpaceOutboxControllerServer interface {
	PatchOutboxMarkAsSentUseCase(context.Context, *MarkRequest) (*emptypb.Empty, error)
	PatchOutboxMarkAsFailedUseCase(context.Context, *MarkFailedRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedPatchHoBomSpaceOutboxControllerServer()
}

// UnimplementedPatchHoBomSpaceOutboxControllerServer must be embedded to have forward compatible implementations.
type UnimplementedPatchHoBomSpaceOutboxControllerServer struct {
}

func (UnimplementedPatchHoBomSpaceOutboxControllerServer) PatchOutboxMarkAsSentUseCase(context.Context, *MarkRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PatchOutboxMarkAsSentUseCase not implemented")
}
func (UnimplementedPatchHoBomSpaceOutboxControllerServer) PatchOutboxMarkAsFailedUseCase(context.Context, *MarkFailedRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PatchOutboxMarkAsFailedUseCase not implemented")
}
func (UnimplementedPatchHoBomSpaceOutboxControllerServer) mustEmbedUnimplementedPatchHoBomSpaceOutboxControllerServer() {
}

// UnsafePatchHoBomSpaceOutboxControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PatchHoBomSpaceOutboxControllerServer will
// result in compilation errors.
type UnsafePatchHoBomSpaceOutboxControllerServer interface {
	mustEmbedUnimplementedPatchHoBomSpaceOutboxControllerServer()
}

func RegisterPatchHoBomSpaceOutboxControllerServer(s grpc.ServiceRegistrar, srv PatchHoBomSpaceOutboxControllerServer) {
	s.RegisterService(&PatchHoBomSpaceOutboxController_ServiceDesc, srv)
}

func _PatchHoBomSpaceOutboxController_PatchOutboxMarkAsSentUseCase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PatchHoBomSpaceOutboxControllerServer).PatchOutboxMarkAsSentUseCase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PatchHoBomSpaceOutboxController_PatchOutboxMarkAsSentUseCase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PatchHoBomSpaceOutboxControllerServer).PatchOutboxMarkAsSentUseCase(ctx, req.(*MarkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PatchHoBomSpaceOutboxController_PatchOutboxMarkAsFailedUseCase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkFailedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PatchHoBomSpaceOutboxControllerServer).PatchOutboxMarkAsFailedUseCase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PatchHoBomSpaceOutboxController_PatchOutboxMarkAsFailedUseCase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PatchHoBomSpaceOutboxControllerServer).PatchOutboxMarkAsFailedUseCase(ctx, req.(*MarkFailedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PatchHoBomSpaceOutboxController_ServiceDesc is the grpc.ServiceDesc for PatchHoBomSpaceOutboxController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PatchHoBomSpaceOutboxController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "outbox.space.PatchHoBomSpaceOutboxController",
	HandlerType: (*PatchHoBomSpaceOutboxControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PatchOutboxMarkAsSentUseCase",
			Handler:    _PatchHoBomSpaceOutboxController_PatchOutboxMarkAsSentUseCase_Handler,
		},
		{
			MethodName: "PatchOutboxMarkAsFailedUseCase",
			Handler:    _PatchHoBomSpaceOutboxController_PatchOutboxMarkAsFailedUseCase_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "space/outbox/v1/patch-hobom-space-outbox.proto",
}
